environment: preprod
replicaCount: 1

vault:
  secretPaths:
    postgres: 
      path: "apps/data/preprod/infra/postgres"
      template: |
        {{- with secret "apps/data/preprod/infra/postgres" -}}
        export POSTGRES_USERNAME="{{ .Data.data.username }}"
        export POSTGRES_PASSWORD="{{ .Data.data.password }}"
        export POSTGRES_PORT="{{ .Data.data.port }}"
        export POSTGRES_HOST="{{ .Data.data.host }}"
        export POSTGRES_DATABASE="portfolio"
        export POSTGRES_URL="jdbc:postgresql://{{ .Data.data.host }}:{{ .Data.data.port }}/portfolio"
        {{- end }}
    mongodb: 
      path: "apps/data/preprod/infra/mongodb"
      template: |
        {{- with secret "apps/data/preprod/infra/mongodb" -}}
        export MONGODB_USERNAME_INTERNAL="{{ .Data.data.username }}"
        export MONGODB_PASSWORD_INTERNAL="{{ .Data.data.password }}"
        export MONGODB_DATABASE_NAME="market_data"
        export INFRA_HOST="{{ .Data.data.host }}"
        export MONGODB_URL="mongodb://{{ .Data.data.username }}:{{ .Data.data.password }}@{{ .Data.data.host }}:{{ .Data.data.port }}/market_data?authSource=admin"
        {{- end }}
    redis: 
      path: "apps/data/preprod/infra/redis"
      template: |
        {{- with secret "apps/data/preprod/infra/redis" -}}
        export REDIS_PASSWORD_INTERNAL="{{ .Data.data.password }}"
        export REDIS_HOSTNAME="{{ .Data.data.host }}"
        export REDIS_PORT="{{ .Data.data.port }}"
        {{- end }}
    influxdb: 
      path: "apps/data/preprod/infra/influxdb"
      template: |
        {{- with secret "apps/data/preprod/infra/influxdb" -}}
        export INFLUXDB_URL_INTERNAL="http://{{ .Data.data.host }}:{{ .Data.data.port }}"
        export INFLUXDB_TOKEN_INTERNAL="{{ .Data.data.token }}"
        export INFLUXDB_ORG_INTERNAL="{{ .Data.data.org }}"
        export INFLUXDB_BUCKET_INTERNAL="{{ .Data.data.bucket }}"
        {{- end }}
    jwt:
      path: "apps/data/preprod/services/am-market-data"
      template: |
        {{- with secret "apps/data/preprod/services/am-market-data" -}}
        export JWT_SECRET="{{ .Data.data.JWT_SECRET_KEY }}"
        {{- end }}
    kafka: 
      path: "apps/data/preprod/infra/kafka"
      template: |
        {{- with secret "apps/data/preprod/infra/kafka" -}}
        export KAFKA_BOOTSTRAP_SERVERS="{{ .Data.data.bootstrap_servers }}"
        export KAFKA_USERNAME="{{ .Data.data.username }}"
        export KAFKA_PASSWORD="{{ .Data.data.password }}"
        {{- end }}
    upstox: 
      path: "apps/data/preprod/services/am-market-data"
      template: |
        {{- with secret "apps/data/preprod/services/am-market-data" -}}
        export UPSTOX_API_KEY="{{ .Data.data.UPSTOX_API_KEY }}"
        export UPSTOX_SECRET_KEY="{{ .Data.data.UPSTOX_SECRET_KEY }}"
        {{- end }}

env:
  SPRING_PROFILES_ACTIVE: "preprod"
  LOG_LEVEL: "INFO"
