env:
  ENVIRONMENT: "preprod"
  MONGO_DB: "mutual_funds"
  MARKET_DATA_URL: "http://am-market-data:8080"
  LOG_LEVEL: "INFO"
  ETF_LIST_CACHE_MINUTES: "60"
  ETF_HOLDINGS_CACHE_DAYS: "1"

environment: preprod

probes:
  port: 8080
  startup:
    path: /health
    timeoutSeconds: 10
    failureThreshold: 30
    periodSeconds: 10
  liveness:
    path: /health
    timeoutSeconds: 10
  readiness:
    path: /health
    timeoutSeconds: 10

replicaCount: 1


# Vault configuration
vault:
  secretPaths:
    auth:
      path: apps/data/preprod/services/am-auth
    logging:
      path: apps/data/preprod/services/logging
    market:
      path: apps/data/preprod/services/am-market-data
    mongodb: 
      path: "apps/data/preprod/infra/mongodb"
    together:
      path: "apps/data/preprod/infra/shared-api"


resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

