environment: dev

replicaCount: 1

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Vault Configuration (Dev Override)
vault:
  secretPaths:
    mongodb: "secret/data/dev/infra/mongodb"
    together: "secret/data/dev/api/together"
