replicaCount: 1
port: 8000
language: python

image:
  repository: am-parser
  pullPolicy: Always

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 1000
  capabilities:
    drop:
      - ALL

# Vault configuration
vault:
  enabled: true
  role: "am-backend-role"
  secretPaths:
    mongodb: "secret/data/preprod/infra/mongodb"
    together: "secret/data/preprod/api/together"

environment: preprod
