environment: prod

replicaCount: 1

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 512Mi

# Vault Configuration (Prod Override)
vault:
  secretPaths:
    mongodb: "secret/data/prod/infra/mongodb"
    together: "secret/data/prod/api/together"
