replicaCount: 1
service:
  port: 8080
language: python

security:
  automountServiceAccountToken: true

global:
  vault:
    serviceAccountName: "am-backend-sa"

image:
  repository: am-parser
  pullPolicy: Always

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 1000
  capabilities:
    drop:
      - ALL

environment: preprod

vault:
  enabled: true
  role: "am-backend-role"
  serviceAccountName: "am-backend-sa"
  secretPaths: {}

# Plane A - Prometheus scrape
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"
  prometheus.io/path: "/metrics"

env:
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://otel-collector.monitoring.svc.cluster.local:4318/v1/traces" 
