vault:
  secretPaths:
    auth:
      mappings:
        JWT_SECRET: "JWT_SECRET"
        INTERNAL_SECRET_KEY: "SECRET_KEY"
    market:
      mappings:
        MARKET_DATA_API_URL: "URL"
    mongodb:
      mappings:
        MONGO_URI: "url"
    together:
      mappings:
        TOGETHER_API_KEY: "TOGETHER_API_KEY"
