# coding: utf-8

"""
    Market Data API Documentation

    API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.

    The version of the OpenAPI document: 1.0.0
    Contact: support@amportfolio.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class InstrumentSearchCriteria(BaseModel):
    """
    InstrumentSearchCriteria
    """ # noqa: E501
    queries: Optional[List[StrictStr]] = None
    exchanges: Optional[List[StrictStr]] = None
    instrument_types: Optional[List[StrictStr]] = Field(default=None, alias="instrumentTypes")
    segments: Optional[List[StrictStr]] = None
    isins: Optional[List[StrictStr]] = None
    trading_symbols: Optional[List[StrictStr]] = Field(default=None, alias="tradingSymbols")
    weekly: Optional[StrictBool] = None
    provider: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["queries", "exchanges", "instrumentTypes", "segments", "isins", "tradingSymbols", "weekly", "provider"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InstrumentSearchCriteria from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InstrumentSearchCriteria from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "queries": obj.get("queries"),
            "exchanges": obj.get("exchanges"),
            "instrumentTypes": obj.get("instrumentTypes"),
            "segments": obj.get("segments"),
            "isins": obj.get("isins"),
            "tradingSymbols": obj.get("tradingSymbols"),
            "weekly": obj.get("weekly"),
            "provider": obj.get("provider")
        })
        return _obj


