# coding: utf-8

"""
    Market Data API Documentation

    API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.

    The version of the OpenAPI document: 1.0.0
    Contact: support@amportfolio.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class Position(BaseModel):
    """
    Position
    """ # noqa: E501
    trading_symbol: Optional[StrictStr] = Field(default=None, alias="tradingSymbol")
    quantity: Optional[StrictInt] = None
    type: Optional[StrictStr] = None
    product: Optional[StrictStr] = None
    exchange: Optional[StrictStr] = None
    price: Optional[Union[StrictFloat, StrictInt]] = None
    option_type: Optional[StrictStr] = Field(default=None, alias="optionType")
    strike_price: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="strikePrice")
    expiry: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["tradingSymbol", "quantity", "type", "product", "exchange", "price", "optionType", "strikePrice", "expiry"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Position from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Position from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tradingSymbol": obj.get("tradingSymbol"),
            "quantity": obj.get("quantity"),
            "type": obj.get("type"),
            "product": obj.get("product"),
            "exchange": obj.get("exchange"),
            "price": obj.get("price"),
            "optionType": obj.get("optionType"),
            "strikePrice": obj.get("strikePrice"),
            "expiry": obj.get("expiry")
        })
        return _obj


