# coding: utf-8

"""
    Market Data API Documentation

    API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.

    The version of the OpenAPI document: 1.0.0
    Contact: support@amportfolio.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class StreamConnectRequest(BaseModel):
    """
    StreamConnectRequest
    """ # noqa: E501
    instrument_keys: Optional[List[StrictStr]] = Field(default=None, alias="instrumentKeys")
    mode: Optional[StrictStr] = None
    expand_indices: Optional[StrictBool] = Field(default=None, alias="expandIndices")
    time_frame: Optional[StrictStr] = Field(default=None, alias="timeFrame")
    is_index_symbol: Optional[StrictBool] = Field(default=None, alias="isIndexSymbol")
    stream: Optional[StrictBool] = None
    provider: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["instrumentKeys", "mode", "expandIndices", "timeFrame", "isIndexSymbol", "stream", "provider"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StreamConnectRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StreamConnectRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "instrumentKeys": obj.get("instrumentKeys"),
            "mode": obj.get("mode"),
            "expandIndices": obj.get("expandIndices"),
            "timeFrame": obj.get("timeFrame"),
            "isIndexSymbol": obj.get("isIndexSymbol"),
            "stream": obj.get("stream"),
            "provider": obj.get("provider")
        })
        return _obj


