version: '3.8'

services:
  market-data-web:
    container_name: market-data-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9002:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.market-ui.rule=Host(`am.munish.org`) && PathPrefix(`/market-ui`)"
      - "traefik.http.routers.market-ui.entrypoints=web"
      - "traefik.http.services.market-ui.loadbalancer.server.port=80"
      - "traefik.http.middlewares.market-strip.stripprefix.prefixes=/market-ui"
      - "traefik.http.routers.market-ui.middlewares=market-strip"
    networks:
      - am-infra_am-net
    restart: unless-stopped

networks:
  am-infra_am-net:
    external: true
