server {
    listen 80;
    server_name localhost;
    absolute_redirect off;

    root /usr/share/nginx/html;
    index index.html index.htm;

    # Redirect root to /market-ui/
    location = / {
        return 301 /market-ui/;
    }

    # Proxy to am-parser-service for ETF data
    location /etf-api/ {
        # Trailing slash is important to strip /etf-api/ prefix
        proxy_pass http://am-parser-service:8000/;
    }

    location /market-ui/ {
        try_files $uri $uri/ /market-ui/index.html;
    }
}
