/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.market.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CookieInfo
 */
class CookieInfoTest {
    private final CookieInfo model = new CookieInfo();

    /**
     * Model tests for CookieInfo
     */
    @Test
    void testCookieInfo() {
        // TODO: test CookieInfo
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'value'
     */
    @Test
    void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'domain'
     */
    @Test
    void domainTest() {
        // TODO: test domain
    }

    /**
     * Test the property 'path'
     */
    @Test
    void pathTest() {
        // TODO: test path
    }

    /**
     * Test the property 'secure'
     */
    @Test
    void secureTest() {
        // TODO: test secure
    }

    /**
     * Test the property 'httpOnly'
     */
    @Test
    void httpOnlyTest() {
        // TODO: test httpOnly
    }

    /**
     * Test the property 'sameSite'
     */
    @Test
    void sameSiteTest() {
        // TODO: test sameSite
    }

    /**
     * Test the property 'expiry'
     */
    @Test
    void expiryTest() {
        // TODO: test expiry
    }

}
