/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.market.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for IngestionJobLog
 */
class IngestionJobLogTest {
    private final IngestionJobLog model = new IngestionJobLog();

    /**
     * Model tests for IngestionJobLog
     */
    @Test
    void testIngestionJobLog() {
        // TODO: test IngestionJobLog
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'jobId'
     */
    @Test
    void jobIdTest() {
        // TODO: test jobId
    }

    /**
     * Test the property 'startTime'
     */
    @Test
    void startTimeTest() {
        // TODO: test startTime
    }

    /**
     * Test the property 'endTime'
     */
    @Test
    void endTimeTest() {
        // TODO: test endTime
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'totalSymbols'
     */
    @Test
    void totalSymbolsTest() {
        // TODO: test totalSymbols
    }

    /**
     * Test the property 'successCount'
     */
    @Test
    void successCountTest() {
        // TODO: test successCount
    }

    /**
     * Test the property 'failureCount'
     */
    @Test
    void failureCountTest() {
        // TODO: test failureCount
    }

    /**
     * Test the property 'failedSymbols'
     */
    @Test
    void failedSymbolsTest() {
        // TODO: test failedSymbols
    }

    /**
     * Test the property 'durationMs'
     */
    @Test
    void durationMsTest() {
        // TODO: test durationMs
    }

    /**
     * Test the property 'payloadSize'
     */
    @Test
    void payloadSizeTest() {
        // TODO: test payloadSize
    }

    /**
     * Test the property 'message'
     */
    @Test
    void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'logs'
     */
    @Test
    void logsTest() {
        // TODO: test logs
    }

}
