/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.market.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for InstrumentSearchCriteria
 */
class InstrumentSearchCriteriaTest {
    private final InstrumentSearchCriteria model = new InstrumentSearchCriteria();

    /**
     * Model tests for InstrumentSearchCriteria
     */
    @Test
    void testInstrumentSearchCriteria() {
        // TODO: test InstrumentSearchCriteria
    }

    /**
     * Test the property 'queries'
     */
    @Test
    void queriesTest() {
        // TODO: test queries
    }

    /**
     * Test the property 'exchanges'
     */
    @Test
    void exchangesTest() {
        // TODO: test exchanges
    }

    /**
     * Test the property 'instrumentTypes'
     */
    @Test
    void instrumentTypesTest() {
        // TODO: test instrumentTypes
    }

    /**
     * Test the property 'segments'
     */
    @Test
    void segmentsTest() {
        // TODO: test segments
    }

    /**
     * Test the property 'isins'
     */
    @Test
    void isinsTest() {
        // TODO: test isins
    }

    /**
     * Test the property 'tradingSymbols'
     */
    @Test
    void tradingSymbolsTest() {
        // TODO: test tradingSymbols
    }

    /**
     * Test the property 'weekly'
     */
    @Test
    void weeklyTest() {
        // TODO: test weekly
    }

    /**
     * Test the property 'provider'
     */
    @Test
    void providerTest() {
        // TODO: test provider
    }

}
