/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.market.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for StockData
 */
class StockDataTest {
    private final StockData model = new StockData();

    /**
     * Model tests for StockData
     */
    @Test
    void testStockData() {
        // TODO: test StockData
    }

    /**
     * Test the property 'symbol'
     */
    @Test
    void symbolTest() {
        // TODO: test symbol
    }

    /**
     * Test the property 'identifier'
     */
    @Test
    void identifierTest() {
        // TODO: test identifier
    }

    /**
     * Test the property 'series'
     */
    @Test
    void seriesTest() {
        // TODO: test series
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'ffmc'
     */
    @Test
    void ffmcTest() {
        // TODO: test ffmc
    }

    /**
     * Test the property 'companyName'
     */
    @Test
    void companyNameTest() {
        // TODO: test companyName
    }

    /**
     * Test the property 'isin'
     */
    @Test
    void isinTest() {
        // TODO: test isin
    }

    /**
     * Test the property 'industry'
     */
    @Test
    void industryTest() {
        // TODO: test industry
    }

}
