/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.market.model;

import com.am.portfolio.client.market.model.AuditData;
import com.am.portfolio.client.market.model.IndexMetadata;
import com.am.portfolio.client.market.model.StockData;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for StockIndicesMarketData
 */
class StockIndicesMarketDataTest {
    private final StockIndicesMarketData model = new StockIndicesMarketData();

    /**
     * Model tests for StockIndicesMarketData
     */
    @Test
    void testStockIndicesMarketData() {
        // TODO: test StockIndicesMarketData
    }

    /**
     * Test the property 'indexSymbol'
     */
    @Test
    void indexSymbolTest() {
        // TODO: test indexSymbol
    }

    /**
     * Test the property 'data'
     */
    @Test
    void dataTest() {
        // TODO: test data
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'docVersion'
     */
    @Test
    void docVersionTest() {
        // TODO: test docVersion
    }

    /**
     * Test the property 'audit'
     */
    @Test
    void auditTest() {
        // TODO: test audit
    }

}
