/*
 * Mutual Fund Portfolio API
 * REST API for managing mutual fund portfolio data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.parser.model;

import com.am.portfolio.client.parser.model.ValidationError;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for HTTPValidationError
 */
class HTTPValidationErrorTest {
    private final HTTPValidationError model = new HTTPValidationError();

    /**
     * Model tests for HTTPValidationError
     */
    @Test
    void testHTTPValidationError() {
        // TODO: test HTTPValidationError
    }

    /**
     * Test the property 'detail'
     */
    @Test
    void detailTest() {
        // TODO: test detail
    }

}
