/*
 * Mutual Fund Portfolio API
 * REST API for managing mutual fund portfolio data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.parser.model;

import com.am.portfolio.client.parser.model.JobStatus;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for JobResponse
 */
class JobResponseTest {
    private final JobResponse model = new JobResponse();

    /**
     * Model tests for JobResponse
     */
    @Test
    void testJobResponse() {
        // TODO: test JobResponse
    }

    /**
     * Test the property 'jobId'
     */
    @Test
    void jobIdTest() {
        // TODO: test jobId
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'message'
     */
    @Test
    void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'estimatedCompletionTime'
     */
    @Test
    void estimatedCompletionTimeTest() {
        // TODO: test estimatedCompletionTime
    }

    /**
     * Test the property 'statusUrl'
     */
    @Test
    void statusUrlTest() {
        // TODO: test statusUrl
    }

    /**
     * Test the property 'webhookUrl'
     */
    @Test
    void webhookUrlTest() {
        // TODO: test webhookUrl
    }

}
