/*
 * Mutual Fund Portfolio API
 * REST API for managing mutual fund portfolio data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.parser.model;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for JobStatus
 */
class JobStatusTest {
    /**
     * Model tests for JobStatus
     */
    @Test
    void testJobStatus() {
        // TODO: test JobStatus
    }

}
