/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.am.portfolio.client.market.api;

import com.am.portfolio.client.market.invoker.ApiClient;
import com.am.portfolio.client.market.invoker.ApiException;
import com.am.portfolio.client.market.invoker.ApiResponse;
import com.am.portfolio.client.market.invoker.Configuration;
import com.am.portfolio.client.market.invoker.Pair;

import com.am.portfolio.client.market.model.HistoricalDataResponseV1;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-27T09:34:10.222147200+05:30[Asia/Calcutta]", comments = "Generator version: 7.18.0")
public class MarketAnalyticsApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public MarketAnalyticsApi() {
    this(Configuration.getDefaultApiClient());
  }

  public MarketAnalyticsApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Get historical charts data
   * Retrieves historical data for charts with various time frames (10m, 1H, 1D, 1W, 1M, 5Y, etc.)
   * @param symbol  (required)
   * @param range  (optional, default to 1D)
   * @return HistoricalDataResponseV1
   * @throws ApiException if fails to make API call
   */
  public HistoricalDataResponseV1 getHistoricalCharts(@javax.annotation.Nonnull String symbol, @javax.annotation.Nullable String range) throws ApiException {
    return getHistoricalCharts(symbol, range, null);
  }

  /**
   * Get historical charts data
   * Retrieves historical data for charts with various time frames (10m, 1H, 1D, 1W, 1M, 5Y, etc.)
   * @param symbol  (required)
   * @param range  (optional, default to 1D)
   * @param headers Optional headers to include in the request
   * @return HistoricalDataResponseV1
   * @throws ApiException if fails to make API call
   */
  public HistoricalDataResponseV1 getHistoricalCharts(@javax.annotation.Nonnull String symbol, @javax.annotation.Nullable String range, Map<String, String> headers) throws ApiException {
    ApiResponse<HistoricalDataResponseV1> localVarResponse = getHistoricalChartsWithHttpInfo(symbol, range, headers);
    return localVarResponse.getData();
  }

  /**
   * Get historical charts data
   * Retrieves historical data for charts with various time frames (10m, 1H, 1D, 1W, 1M, 5Y, etc.)
   * @param symbol  (required)
   * @param range  (optional, default to 1D)
   * @return ApiResponse&lt;HistoricalDataResponseV1&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<HistoricalDataResponseV1> getHistoricalChartsWithHttpInfo(@javax.annotation.Nonnull String symbol, @javax.annotation.Nullable String range) throws ApiException {
    return getHistoricalChartsWithHttpInfo(symbol, range, null);
  }

  /**
   * Get historical charts data
   * Retrieves historical data for charts with various time frames (10m, 1H, 1D, 1W, 1M, 5Y, etc.)
   * @param symbol  (required)
   * @param range  (optional, default to 1D)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;HistoricalDataResponseV1&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<HistoricalDataResponseV1> getHistoricalChartsWithHttpInfo(@javax.annotation.Nonnull String symbol, @javax.annotation.Nullable String range, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getHistoricalChartsRequestBuilder(symbol, range, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getHistoricalCharts", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<HistoricalDataResponseV1>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        HistoricalDataResponseV1 responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<HistoricalDataResponseV1>() {});
        

        return new ApiResponse<HistoricalDataResponseV1>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getHistoricalChartsRequestBuilder(@javax.annotation.Nonnull String symbol, @javax.annotation.Nullable String range, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'symbol' is set
    if (symbol == null) {
      throw new ApiException(400, "Missing the required parameter 'symbol' when calling getHistoricalCharts");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/market-analytics/historical-charts/{symbol}"
        .replace("{symbol}", ApiClient.urlEncode(symbol.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "range";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("range", range));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get Top Gainers/Losers
   * Retrieves top performing or worst performing stocks from the specified market index
   * @param type  (optional, default to gainers)
   * @param limit  (optional, default to 10)
   * @param indexSymbol  (optional)
   * @param timeFrame  (optional)
   * @param expandIndices  (optional, default to false)
   * @return List&lt;Map&lt;String, Object&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public List<Map<String, Object>> getMovers(@javax.annotation.Nullable String type, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String indexSymbol, @javax.annotation.Nullable String timeFrame, @javax.annotation.Nullable Boolean expandIndices) throws ApiException {
    return getMovers(type, limit, indexSymbol, timeFrame, expandIndices, null);
  }

  /**
   * Get Top Gainers/Losers
   * Retrieves top performing or worst performing stocks from the specified market index
   * @param type  (optional, default to gainers)
   * @param limit  (optional, default to 10)
   * @param indexSymbol  (optional)
   * @param timeFrame  (optional)
   * @param expandIndices  (optional, default to false)
   * @param headers Optional headers to include in the request
   * @return List&lt;Map&lt;String, Object&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public List<Map<String, Object>> getMovers(@javax.annotation.Nullable String type, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String indexSymbol, @javax.annotation.Nullable String timeFrame, @javax.annotation.Nullable Boolean expandIndices, Map<String, String> headers) throws ApiException {
    ApiResponse<List<Map<String, Object>>> localVarResponse = getMoversWithHttpInfo(type, limit, indexSymbol, timeFrame, expandIndices, headers);
    return localVarResponse.getData();
  }

  /**
   * Get Top Gainers/Losers
   * Retrieves top performing or worst performing stocks from the specified market index
   * @param type  (optional, default to gainers)
   * @param limit  (optional, default to 10)
   * @param indexSymbol  (optional)
   * @param timeFrame  (optional)
   * @param expandIndices  (optional, default to false)
   * @return ApiResponse&lt;List&lt;Map&lt;String, Object&gt;&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<Map<String, Object>>> getMoversWithHttpInfo(@javax.annotation.Nullable String type, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String indexSymbol, @javax.annotation.Nullable String timeFrame, @javax.annotation.Nullable Boolean expandIndices) throws ApiException {
    return getMoversWithHttpInfo(type, limit, indexSymbol, timeFrame, expandIndices, null);
  }

  /**
   * Get Top Gainers/Losers
   * Retrieves top performing or worst performing stocks from the specified market index
   * @param type  (optional, default to gainers)
   * @param limit  (optional, default to 10)
   * @param indexSymbol  (optional)
   * @param timeFrame  (optional)
   * @param expandIndices  (optional, default to false)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;List&lt;Map&lt;String, Object&gt;&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<Map<String, Object>>> getMoversWithHttpInfo(@javax.annotation.Nullable String type, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String indexSymbol, @javax.annotation.Nullable String timeFrame, @javax.annotation.Nullable Boolean expandIndices, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getMoversRequestBuilder(type, limit, indexSymbol, timeFrame, expandIndices, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getMovers", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<List<Map<String, Object>>>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        List<Map<String, Object>> responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<List<Map<String, Object>>>() {});
        

        return new ApiResponse<List<Map<String, Object>>>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getMoversRequestBuilder(@javax.annotation.Nullable String type, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String indexSymbol, @javax.annotation.Nullable String timeFrame, @javax.annotation.Nullable Boolean expandIndices, Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/market-analytics/movers";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "type";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("type", type));
    localVarQueryParameterBaseName = "limit";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("limit", limit));
    localVarQueryParameterBaseName = "indexSymbol";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("indexSymbol", indexSymbol));
    localVarQueryParameterBaseName = "timeFrame";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("timeFrame", timeFrame));
    localVarQueryParameterBaseName = "expandIndices";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("expandIndices", expandIndices));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get Sector Performance
   * Aggregates market performance by sector (Industry) from the specified index
   * @param indexSymbol  (optional)
   * @param timeFrame  (optional)
   * @param expandIndices  (optional, default to false)
   * @return List&lt;Map&lt;String, Object&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public List<Map<String, Object>> getSectorPerformance(@javax.annotation.Nullable String indexSymbol, @javax.annotation.Nullable String timeFrame, @javax.annotation.Nullable Boolean expandIndices) throws ApiException {
    return getSectorPerformance(indexSymbol, timeFrame, expandIndices, null);
  }

  /**
   * Get Sector Performance
   * Aggregates market performance by sector (Industry) from the specified index
   * @param indexSymbol  (optional)
   * @param timeFrame  (optional)
   * @param expandIndices  (optional, default to false)
   * @param headers Optional headers to include in the request
   * @return List&lt;Map&lt;String, Object&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public List<Map<String, Object>> getSectorPerformance(@javax.annotation.Nullable String indexSymbol, @javax.annotation.Nullable String timeFrame, @javax.annotation.Nullable Boolean expandIndices, Map<String, String> headers) throws ApiException {
    ApiResponse<List<Map<String, Object>>> localVarResponse = getSectorPerformanceWithHttpInfo(indexSymbol, timeFrame, expandIndices, headers);
    return localVarResponse.getData();
  }

  /**
   * Get Sector Performance
   * Aggregates market performance by sector (Industry) from the specified index
   * @param indexSymbol  (optional)
   * @param timeFrame  (optional)
   * @param expandIndices  (optional, default to false)
   * @return ApiResponse&lt;List&lt;Map&lt;String, Object&gt;&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<Map<String, Object>>> getSectorPerformanceWithHttpInfo(@javax.annotation.Nullable String indexSymbol, @javax.annotation.Nullable String timeFrame, @javax.annotation.Nullable Boolean expandIndices) throws ApiException {
    return getSectorPerformanceWithHttpInfo(indexSymbol, timeFrame, expandIndices, null);
  }

  /**
   * Get Sector Performance
   * Aggregates market performance by sector (Industry) from the specified index
   * @param indexSymbol  (optional)
   * @param timeFrame  (optional)
   * @param expandIndices  (optional, default to false)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;List&lt;Map&lt;String, Object&gt;&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<Map<String, Object>>> getSectorPerformanceWithHttpInfo(@javax.annotation.Nullable String indexSymbol, @javax.annotation.Nullable String timeFrame, @javax.annotation.Nullable Boolean expandIndices, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getSectorPerformanceRequestBuilder(indexSymbol, timeFrame, expandIndices, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getSectorPerformance", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<List<Map<String, Object>>>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        List<Map<String, Object>> responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<List<Map<String, Object>>>() {});
        

        return new ApiResponse<List<Map<String, Object>>>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getSectorPerformanceRequestBuilder(@javax.annotation.Nullable String indexSymbol, @javax.annotation.Nullable String timeFrame, @javax.annotation.Nullable Boolean expandIndices, Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/market-analytics/sectors";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "indexSymbol";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("indexSymbol", indexSymbol));
    localVarQueryParameterBaseName = "timeFrame";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("timeFrame", timeFrame));
    localVarQueryParameterBaseName = "expandIndices";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("expandIndices", expandIndices));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
