/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.am.portfolio.client.market.api;

import com.am.portfolio.client.market.invoker.ApiClient;
import com.am.portfolio.client.market.invoker.ApiException;
import com.am.portfolio.client.market.invoker.ApiResponse;
import com.am.portfolio.client.market.invoker.Configuration;
import com.am.portfolio.client.market.invoker.Pair;

import com.am.portfolio.client.market.model.IngestionJobLog;
import java.time.LocalDate;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-27T02:29:36.319987700+05:30[Asia/Calcutta]", comments = "Generator version: 7.18.0")
public class MarketDataAdminControllerApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public MarketDataAdminControllerApi() {
    this(Configuration.getDefaultApiClient());
  }

  public MarketDataAdminControllerApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * 
   * 
   * @param jobId  (required)
   * @return IngestionJobLog
   * @throws ApiException if fails to make API call
   */
  public IngestionJobLog getJobDetails(@javax.annotation.Nonnull String jobId) throws ApiException {
    return getJobDetails(jobId, null);
  }

  /**
   * 
   * 
   * @param jobId  (required)
   * @param headers Optional headers to include in the request
   * @return IngestionJobLog
   * @throws ApiException if fails to make API call
   */
  public IngestionJobLog getJobDetails(@javax.annotation.Nonnull String jobId, Map<String, String> headers) throws ApiException {
    ApiResponse<IngestionJobLog> localVarResponse = getJobDetailsWithHttpInfo(jobId, headers);
    return localVarResponse.getData();
  }

  /**
   * 
   * 
   * @param jobId  (required)
   * @return ApiResponse&lt;IngestionJobLog&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<IngestionJobLog> getJobDetailsWithHttpInfo(@javax.annotation.Nonnull String jobId) throws ApiException {
    return getJobDetailsWithHttpInfo(jobId, null);
  }

  /**
   * 
   * 
   * @param jobId  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;IngestionJobLog&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<IngestionJobLog> getJobDetailsWithHttpInfo(@javax.annotation.Nonnull String jobId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getJobDetailsRequestBuilder(jobId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getJobDetails", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<IngestionJobLog>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        IngestionJobLog responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<IngestionJobLog>() {});
        

        return new ApiResponse<IngestionJobLog>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getJobDetailsRequestBuilder(@javax.annotation.Nonnull String jobId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'jobId' is set
    if (jobId == null) {
      throw new ApiException(400, "Missing the required parameter 'jobId' when calling getJobDetails");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/admin/logs/{jobId}"
        .replace("{jobId}", ApiClient.urlEncode(jobId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "*/*");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 
   * 
   * @param page  (optional, default to 0)
   * @param size  (optional, default to 10)
   * @param startDate  (optional)
   * @param endDate  (optional)
   * @return List&lt;IngestionJobLog&gt;
   * @throws ApiException if fails to make API call
   */
  public List<IngestionJobLog> getLogs(@javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer size, @javax.annotation.Nullable LocalDate startDate, @javax.annotation.Nullable LocalDate endDate) throws ApiException {
    return getLogs(page, size, startDate, endDate, null);
  }

  /**
   * 
   * 
   * @param page  (optional, default to 0)
   * @param size  (optional, default to 10)
   * @param startDate  (optional)
   * @param endDate  (optional)
   * @param headers Optional headers to include in the request
   * @return List&lt;IngestionJobLog&gt;
   * @throws ApiException if fails to make API call
   */
  public List<IngestionJobLog> getLogs(@javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer size, @javax.annotation.Nullable LocalDate startDate, @javax.annotation.Nullable LocalDate endDate, Map<String, String> headers) throws ApiException {
    ApiResponse<List<IngestionJobLog>> localVarResponse = getLogsWithHttpInfo(page, size, startDate, endDate, headers);
    return localVarResponse.getData();
  }

  /**
   * 
   * 
   * @param page  (optional, default to 0)
   * @param size  (optional, default to 10)
   * @param startDate  (optional)
   * @param endDate  (optional)
   * @return ApiResponse&lt;List&lt;IngestionJobLog&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<IngestionJobLog>> getLogsWithHttpInfo(@javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer size, @javax.annotation.Nullable LocalDate startDate, @javax.annotation.Nullable LocalDate endDate) throws ApiException {
    return getLogsWithHttpInfo(page, size, startDate, endDate, null);
  }

  /**
   * 
   * 
   * @param page  (optional, default to 0)
   * @param size  (optional, default to 10)
   * @param startDate  (optional)
   * @param endDate  (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;List&lt;IngestionJobLog&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<IngestionJobLog>> getLogsWithHttpInfo(@javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer size, @javax.annotation.Nullable LocalDate startDate, @javax.annotation.Nullable LocalDate endDate, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getLogsRequestBuilder(page, size, startDate, endDate, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getLogs", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<List<IngestionJobLog>>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        List<IngestionJobLog> responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<List<IngestionJobLog>>() {});
        

        return new ApiResponse<List<IngestionJobLog>>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getLogsRequestBuilder(@javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer size, @javax.annotation.Nullable LocalDate startDate, @javax.annotation.Nullable LocalDate endDate, Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/admin/logs";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "page";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("page", page));
    localVarQueryParameterBaseName = "size";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("size", size));
    localVarQueryParameterBaseName = "startDate";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("startDate", startDate));
    localVarQueryParameterBaseName = "endDate";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("endDate", endDate));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "*/*");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 
   * 
   * @param provider  (optional, default to UPSTOX)
   * @param symbols  (optional)
   * @return String
   * @throws ApiException if fails to make API call
   */
  public String startIngestion(@javax.annotation.Nullable String provider, @javax.annotation.Nullable List<String> symbols) throws ApiException {
    return startIngestion(provider, symbols, null);
  }

  /**
   * 
   * 
   * @param provider  (optional, default to UPSTOX)
   * @param symbols  (optional)
   * @param headers Optional headers to include in the request
   * @return String
   * @throws ApiException if fails to make API call
   */
  public String startIngestion(@javax.annotation.Nullable String provider, @javax.annotation.Nullable List<String> symbols, Map<String, String> headers) throws ApiException {
    ApiResponse<String> localVarResponse = startIngestionWithHttpInfo(provider, symbols, headers);
    return localVarResponse.getData();
  }

  /**
   * 
   * 
   * @param provider  (optional, default to UPSTOX)
   * @param symbols  (optional)
   * @return ApiResponse&lt;String&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<String> startIngestionWithHttpInfo(@javax.annotation.Nullable String provider, @javax.annotation.Nullable List<String> symbols) throws ApiException {
    return startIngestionWithHttpInfo(provider, symbols, null);
  }

  /**
   * 
   * 
   * @param provider  (optional, default to UPSTOX)
   * @param symbols  (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;String&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<String> startIngestionWithHttpInfo(@javax.annotation.Nullable String provider, @javax.annotation.Nullable List<String> symbols, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = startIngestionRequestBuilder(provider, symbols, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("startIngestion", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<String>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        String responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<String>() {});
        

        return new ApiResponse<String>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder startIngestionRequestBuilder(@javax.annotation.Nullable String provider, @javax.annotation.Nullable List<String> symbols, Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/admin/ingestion/start";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "provider";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("provider", provider));
    localVarQueryParameterBaseName = "symbols";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("multi", "symbols", symbols));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "*/*");

    localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 
   * 
   * @param provider  (required)
   * @return String
   * @throws ApiException if fails to make API call
   */
  public String stopIngestion(@javax.annotation.Nonnull String provider) throws ApiException {
    return stopIngestion(provider, null);
  }

  /**
   * 
   * 
   * @param provider  (required)
   * @param headers Optional headers to include in the request
   * @return String
   * @throws ApiException if fails to make API call
   */
  public String stopIngestion(@javax.annotation.Nonnull String provider, Map<String, String> headers) throws ApiException {
    ApiResponse<String> localVarResponse = stopIngestionWithHttpInfo(provider, headers);
    return localVarResponse.getData();
  }

  /**
   * 
   * 
   * @param provider  (required)
   * @return ApiResponse&lt;String&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<String> stopIngestionWithHttpInfo(@javax.annotation.Nonnull String provider) throws ApiException {
    return stopIngestionWithHttpInfo(provider, null);
  }

  /**
   * 
   * 
   * @param provider  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;String&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<String> stopIngestionWithHttpInfo(@javax.annotation.Nonnull String provider, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = stopIngestionRequestBuilder(provider, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("stopIngestion", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<String>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        String responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<String>() {});
        

        return new ApiResponse<String>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder stopIngestionRequestBuilder(@javax.annotation.Nonnull String provider, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'provider' is set
    if (provider == null) {
      throw new ApiException(400, "Missing the required parameter 'provider' when calling stopIngestion");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/admin/ingestion/stop";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "provider";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("provider", provider));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "*/*");

    localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 
   * 
   * @param symbol  (optional)
   * @param forceRefresh  (optional, default to true)
   * @param fetchIndexStocks  (optional, default to false)
   * @return String
   * @throws ApiException if fails to make API call
   */
  public String triggerHistoricalSync(@javax.annotation.Nullable String symbol, @javax.annotation.Nullable Boolean forceRefresh, @javax.annotation.Nullable Boolean fetchIndexStocks) throws ApiException {
    return triggerHistoricalSync(symbol, forceRefresh, fetchIndexStocks, null);
  }

  /**
   * 
   * 
   * @param symbol  (optional)
   * @param forceRefresh  (optional, default to true)
   * @param fetchIndexStocks  (optional, default to false)
   * @param headers Optional headers to include in the request
   * @return String
   * @throws ApiException if fails to make API call
   */
  public String triggerHistoricalSync(@javax.annotation.Nullable String symbol, @javax.annotation.Nullable Boolean forceRefresh, @javax.annotation.Nullable Boolean fetchIndexStocks, Map<String, String> headers) throws ApiException {
    ApiResponse<String> localVarResponse = triggerHistoricalSyncWithHttpInfo(symbol, forceRefresh, fetchIndexStocks, headers);
    return localVarResponse.getData();
  }

  /**
   * 
   * 
   * @param symbol  (optional)
   * @param forceRefresh  (optional, default to true)
   * @param fetchIndexStocks  (optional, default to false)
   * @return ApiResponse&lt;String&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<String> triggerHistoricalSyncWithHttpInfo(@javax.annotation.Nullable String symbol, @javax.annotation.Nullable Boolean forceRefresh, @javax.annotation.Nullable Boolean fetchIndexStocks) throws ApiException {
    return triggerHistoricalSyncWithHttpInfo(symbol, forceRefresh, fetchIndexStocks, null);
  }

  /**
   * 
   * 
   * @param symbol  (optional)
   * @param forceRefresh  (optional, default to true)
   * @param fetchIndexStocks  (optional, default to false)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;String&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<String> triggerHistoricalSyncWithHttpInfo(@javax.annotation.Nullable String symbol, @javax.annotation.Nullable Boolean forceRefresh, @javax.annotation.Nullable Boolean fetchIndexStocks, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = triggerHistoricalSyncRequestBuilder(symbol, forceRefresh, fetchIndexStocks, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("triggerHistoricalSync", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<String>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        String responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<String>() {});
        

        return new ApiResponse<String>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder triggerHistoricalSyncRequestBuilder(@javax.annotation.Nullable String symbol, @javax.annotation.Nullable Boolean forceRefresh, @javax.annotation.Nullable Boolean fetchIndexStocks, Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/admin/sync/historical";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "symbol";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("symbol", symbol));
    localVarQueryParameterBaseName = "forceRefresh";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("forceRefresh", forceRefresh));
    localVarQueryParameterBaseName = "fetchIndexStocks";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("fetchIndexStocks", fetchIndexStocks));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "*/*");

    localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
