/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.market.api;

import com.am.portfolio.client.market.invoker.ApiException;
import com.am.portfolio.client.market.model.BrokerageCalculationRequest;
import com.am.portfolio.client.market.model.BrokerageCalculationResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for BrokerageCalculatorApi
 */
@Disabled
public class BrokerageCalculatorApiTest {

    private final BrokerageCalculatorApi api = new BrokerageCalculatorApi();

    
    /**
     * Calculate breakeven price
     *
     * Calculate the breakeven price for a stock considering all charges
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void calculateBreakevenTest() throws ApiException {
        String symbol = null;
        Double price = null;
        Integer quantity = null;
        String exchange = null;
        String tradeType = null;
        String brokerType = null;
        BrokerageCalculationResponse response = 
        api.calculateBreakeven(symbol, price, quantity, exchange, tradeType, brokerType);
        
        // TODO: test validations
    }
    
    /**
     * Calculate brokerage and taxes
     *
     * Calculate brokerage, STT, GST, exchange charges, SEBI charges, stamp duty, and DP charges for a trade
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void calculateBrokerageTest() throws ApiException {
        BrokerageCalculationRequest brokerageCalculationRequest = null;
        BrokerageCalculationResponse response = 
        api.calculateBrokerage(brokerageCalculationRequest);
        
        // TODO: test validations
    }
    
    /**
     * Calculate brokerage and taxes asynchronously
     *
     * Asynchronously calculate brokerage, STT, GST, exchange charges, SEBI charges, stamp duty, and DP charges for a trade
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void calculateBrokerageAsyncTest() throws ApiException {
        BrokerageCalculationRequest brokerageCalculationRequest = null;
        BrokerageCalculationResponse response = 
        api.calculateBrokerageAsync(brokerageCalculationRequest);
        
        // TODO: test validations
    }
    
}
