/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.market.api;

import com.am.portfolio.client.market.invoker.ApiException;
import com.am.portfolio.client.market.model.HistoricalDataResponseV1;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for MarketAnalyticsApi
 */
@Disabled
public class MarketAnalyticsApiTest {

    private final MarketAnalyticsApi api = new MarketAnalyticsApi();

    
    /**
     * Get historical charts data
     *
     * Retrieves historical data for charts with various time frames (10m, 1H, 1D, 1W, 1M, 5Y, etc.)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getHistoricalChartsTest() throws ApiException {
        String symbol = null;
        String range = null;
        HistoricalDataResponseV1 response = 
        api.getHistoricalCharts(symbol, range);
        
        // TODO: test validations
    }
    
    /**
     * Get Top Gainers/Losers
     *
     * Retrieves top performing or worst performing stocks from the specified market index
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMoversTest() throws ApiException {
        String type = null;
        Integer limit = null;
        String indexSymbol = null;
        String timeFrame = null;
        Boolean expandIndices = null;
        List<Map<String, Object>> response = 
        api.getMovers(type, limit, indexSymbol, timeFrame, expandIndices);
        
        // TODO: test validations
    }
    
    /**
     * Get Sector Performance
     *
     * Aggregates market performance by sector (Industry) from the specified index
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSectorPerformanceTest() throws ApiException {
        String indexSymbol = null;
        String timeFrame = null;
        Boolean expandIndices = null;
        List<Map<String, Object>> response = 
        api.getSectorPerformance(indexSymbol, timeFrame, expandIndices);
        
        // TODO: test validations
    }
    
}
