/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.market.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.portfolio.client.market.invoker.ApiClient;
/**
 * QuoteChange
 */
@JsonPropertyOrder({
  QuoteChange.JSON_PROPERTY_LAST_PRICE,
  QuoteChange.JSON_PROPERTY_OPEN,
  QuoteChange.JSON_PROPERTY_HIGH,
  QuoteChange.JSON_PROPERTY_LOW,
  QuoteChange.JSON_PROPERTY_CLOSE,
  QuoteChange.JSON_PROPERTY_PREVIOUS_CLOSE,
  QuoteChange.JSON_PROPERTY_CHANGE,
  QuoteChange.JSON_PROPERTY_CHANGE_PERCENT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-09T00:34:57.270907600+05:30[Asia/Calcutta]", comments = "Generator version: 7.18.0")
public class QuoteChange {
  public static final String JSON_PROPERTY_LAST_PRICE = "lastPrice";
  @javax.annotation.Nullable
  private Double lastPrice;

  public static final String JSON_PROPERTY_OPEN = "open";
  @javax.annotation.Nullable
  private Double open;

  public static final String JSON_PROPERTY_HIGH = "high";
  @javax.annotation.Nullable
  private Double high;

  public static final String JSON_PROPERTY_LOW = "low";
  @javax.annotation.Nullable
  private Double low;

  public static final String JSON_PROPERTY_CLOSE = "close";
  @javax.annotation.Nullable
  private Double close;

  public static final String JSON_PROPERTY_PREVIOUS_CLOSE = "previousClose";
  @javax.annotation.Nullable
  private Double previousClose;

  public static final String JSON_PROPERTY_CHANGE = "change";
  @javax.annotation.Nullable
  private Double change;

  public static final String JSON_PROPERTY_CHANGE_PERCENT = "changePercent";
  @javax.annotation.Nullable
  private Double changePercent;

  public QuoteChange() { 
  }

  public QuoteChange lastPrice(@javax.annotation.Nullable Double lastPrice) {
    this.lastPrice = lastPrice;
    return this;
  }

  /**
   * Get lastPrice
   * @return lastPrice
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LAST_PRICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getLastPrice() {
    return lastPrice;
  }


  @JsonProperty(value = JSON_PROPERTY_LAST_PRICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastPrice(@javax.annotation.Nullable Double lastPrice) {
    this.lastPrice = lastPrice;
  }


  public QuoteChange open(@javax.annotation.Nullable Double open) {
    this.open = open;
    return this;
  }

  /**
   * Get open
   * @return open
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OPEN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getOpen() {
    return open;
  }


  @JsonProperty(value = JSON_PROPERTY_OPEN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOpen(@javax.annotation.Nullable Double open) {
    this.open = open;
  }


  public QuoteChange high(@javax.annotation.Nullable Double high) {
    this.high = high;
    return this;
  }

  /**
   * Get high
   * @return high
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HIGH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getHigh() {
    return high;
  }


  @JsonProperty(value = JSON_PROPERTY_HIGH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHigh(@javax.annotation.Nullable Double high) {
    this.high = high;
  }


  public QuoteChange low(@javax.annotation.Nullable Double low) {
    this.low = low;
    return this;
  }

  /**
   * Get low
   * @return low
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LOW, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getLow() {
    return low;
  }


  @JsonProperty(value = JSON_PROPERTY_LOW, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLow(@javax.annotation.Nullable Double low) {
    this.low = low;
  }


  public QuoteChange close(@javax.annotation.Nullable Double close) {
    this.close = close;
    return this;
  }

  /**
   * Get close
   * @return close
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CLOSE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getClose() {
    return close;
  }


  @JsonProperty(value = JSON_PROPERTY_CLOSE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClose(@javax.annotation.Nullable Double close) {
    this.close = close;
  }


  public QuoteChange previousClose(@javax.annotation.Nullable Double previousClose) {
    this.previousClose = previousClose;
    return this;
  }

  /**
   * Get previousClose
   * @return previousClose
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PREVIOUS_CLOSE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getPreviousClose() {
    return previousClose;
  }


  @JsonProperty(value = JSON_PROPERTY_PREVIOUS_CLOSE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPreviousClose(@javax.annotation.Nullable Double previousClose) {
    this.previousClose = previousClose;
  }


  public QuoteChange change(@javax.annotation.Nullable Double change) {
    this.change = change;
    return this;
  }

  /**
   * Get change
   * @return change
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CHANGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getChange() {
    return change;
  }


  @JsonProperty(value = JSON_PROPERTY_CHANGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChange(@javax.annotation.Nullable Double change) {
    this.change = change;
  }


  public QuoteChange changePercent(@javax.annotation.Nullable Double changePercent) {
    this.changePercent = changePercent;
    return this;
  }

  /**
   * Get changePercent
   * @return changePercent
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CHANGE_PERCENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getChangePercent() {
    return changePercent;
  }


  @JsonProperty(value = JSON_PROPERTY_CHANGE_PERCENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChangePercent(@javax.annotation.Nullable Double changePercent) {
    this.changePercent = changePercent;
  }


  /**
   * Return true if this QuoteChange object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QuoteChange quoteChange = (QuoteChange) o;
    return Objects.equals(this.lastPrice, quoteChange.lastPrice) &&
        Objects.equals(this.open, quoteChange.open) &&
        Objects.equals(this.high, quoteChange.high) &&
        Objects.equals(this.low, quoteChange.low) &&
        Objects.equals(this.close, quoteChange.close) &&
        Objects.equals(this.previousClose, quoteChange.previousClose) &&
        Objects.equals(this.change, quoteChange.change) &&
        Objects.equals(this.changePercent, quoteChange.changePercent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lastPrice, open, high, low, close, previousClose, change, changePercent);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QuoteChange {\n");
    sb.append("    lastPrice: ").append(toIndentedString(lastPrice)).append("\n");
    sb.append("    open: ").append(toIndentedString(open)).append("\n");
    sb.append("    high: ").append(toIndentedString(high)).append("\n");
    sb.append("    low: ").append(toIndentedString(low)).append("\n");
    sb.append("    close: ").append(toIndentedString(close)).append("\n");
    sb.append("    previousClose: ").append(toIndentedString(previousClose)).append("\n");
    sb.append("    change: ").append(toIndentedString(change)).append("\n");
    sb.append("    changePercent: ").append(toIndentedString(changePercent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `lastPrice` to the URL query string
    if (getLastPrice() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slastPrice%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLastPrice()))));
    }

    // add `open` to the URL query string
    if (getOpen() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sopen%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOpen()))));
    }

    // add `high` to the URL query string
    if (getHigh() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%shigh%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHigh()))));
    }

    // add `low` to the URL query string
    if (getLow() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slow%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLow()))));
    }

    // add `close` to the URL query string
    if (getClose() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sclose%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getClose()))));
    }

    // add `previousClose` to the URL query string
    if (getPreviousClose() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spreviousClose%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPreviousClose()))));
    }

    // add `change` to the URL query string
    if (getChange() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%schange%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getChange()))));
    }

    // add `changePercent` to the URL query string
    if (getChangePercent() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%schangePercent%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getChangePercent()))));
    }

    return joiner.toString();
  }
}

