apiVersion: am.argocd/v1
kind: ServiceDeploy
service: am-market-data
enabled: true
owners: market
source:
  repo: am-market
  path: am-market-data/argocd.yaml
chart:
  repoURL: https://github.com/AM-Portfolio/am-pipelines.git
  path: am-market-data/argocd.yaml
  targetRevision: main
helm:
  releaseName: am-market-data
  valuesPath: am-market-data/helm
valuesRepoURL: https://github.com/AM-Portfolio/am-market.git
valuesTargetRevision: main
envs:
  prod:
    enabled: true
    namespace: am-apps-prod
