package com.am.marketdata.config;

import com.influxdb.client.InfluxDBClient;
import com.influxdb.client.InfluxDBClientFactory;
import com.influxdb.client.InfluxDBClientOptions;
import io.micrometer.observation.ObservationRegistry;
import io.micrometer.observation.transport.http.OkHttpObservationInterceptor;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Custom InfluxDB Configuration with Micrometer Distributed Tracing.
 * 
 * Intercepts OkHttp queries generated by InfluxDBClient and creates spans
 * to visualize InfluxDB requests in Tempo.
 */
@Configuration
public class InfluxDBConfig {

    @Value("${spring.influx.url}")
    private String url;

    @Value("${spring.influx.token}")
    private String token;

    @Value("${spring.influx.org}")
    private String org;

    @Value("${spring.influx.bucket}")
    private String bucket;

    @Bean
    public InfluxDBClient influxDBClient(ObjectProvider<ObservationRegistry> observationRegistryProvider) {
        okhttp3.OkHttpClient.Builder okHttpClientBuilder = new okhttp3.OkHttpClient.Builder();

        ObservationRegistry registry = observationRegistryProvider.getIfAvailable();
        if (registry != null) {
            okHttpClientBuilder.addInterceptor(
                OkHttpObservationInterceptor.builder(registry, "influxdb.requests").build()
            );
        }

        InfluxDBClientOptions options = InfluxDBClientOptions.builder()
                .url(url)
                .authenticateToken(token.toCharArray())
                .org(org)
                .bucket(bucket)
                .okHttpClient(okHttpClientBuilder)
                .build();

        return InfluxDBClientFactory.create(options);
    }

    public String getBucket() {
        return bucket;
    }

    public String getOrg() {
        return org;
    }
}
