apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "am-parser.fullname" . }}
  labels:
    app: {{ include "am-parser.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "am-parser.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "am-parser.name" . }}
        environment: {{ .Values.environment }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.global.image.registry }}/{{ .Values.image.repository }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
