vault:
  secretPaths:
    mongodb:
      mappings:
        MONGO_URI: "url"
    redis:
      mappings:
        REDIS_HOSTNAME: "host"
        REDIS_PASSWORD: "password"
        REDIS_PORT: "port"
    identity-oidc:
      mappings:
        OIDC_JWKS_URL: "OIDC_JWKS_URL"
        OIDC_ISSUER: "OIDC_ISSUER"
    market:
      mappings:
        JWT_SECRET: "JWT_SECRET_KEY"
        UPSTOX_ACCESS_TOKEN: "UPSTOCK_ACCESS_TOKEN"
    otel:
      mappings:
        TRACING_SAMPLING_PROBABILITY: "TRACING_SAMPLING_PROBABILITY"
