INFRA_HOST: 100.72.208.15

# Kafka Configuration
KAFKA_BOOTSTRAP_SERVERS: localhost:9092 #${INFRA_HOST}:9092

# Application-specific Kafka properties Here you can there you go
app:
  kafka:
    enabled: true
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    properties:
      securityProtocol: ${KAFKA_SECURITY_PROTOCOL:SASL_PLAINTEXT}
      saslMechanism: ${KAFKA_SASL_MECHANISM:SCRAM-SHA-256}
      saslJaasConfig: org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";

    # Topic configuration
    topics:
      stock-price: ${STOKUPATE_TOPIC_NAME:am-stock-price-update}
      market-data-ohlc-ingestion: ${MARKET_DATA_OHLC_INGESTION_TOPIC_NAME:market-data-ohlc-ingestion}
      market-data-historical-ingestion: ${MARKET_DATA_HISTORICAL_INGESTION_TOPIC_NAME:market-data-historical-ingestion}
      nse-indices: ${NSE_INDICES_TOPIC_NAME:am-nse-indices}
      stock-indices: ${NSE_STOCK_INDICES_TOPIC_NAME:am-stock-indices}
      stock-board-of-directors: ${BOARD_OF_DIRECTORS_TOPIC_NAME:stock-board-of-directors}
      stock-quaterly-financials: ${QUATERLY_FINANCIALS_TOPIC_NAME:stock-quaterly-financials}
      stock-balance-sheet-financials: ${STOCK_BALANCE_SHEET_FINANCIALS_TOPIC_NAME:stock-balance-sheet-financials}
      stock-cash-flow-financials: ${STOCK_CASH_FLOW_FINANCIALS_TOPIC_NAME:stock-cash-flow-financials}
      stock-profit-and-loss-financials: ${STOCK_PROFIT_AND_LOSS_FINANCIALS_TOPIC_NAME:stock-profit-and-loss-financials}
      stock-results-financials: ${STOCK_RESULTS_FINANCIALS_TOPIC_NAME:stock-results-financials}
      stock-factsheet-dividend-financials: ${STOCK_FACT_SHEET_DIVIDEND_FINANCIALS_TOPIC_NAME:stock-fact-sheet-dividend-financials}

    # Producer configuration
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      batch-size: 16384
      linger-ms: 1
      buffer-memory: 33554432
