/*
 * Mutual Fund Portfolio API
 * REST API for managing mutual fund portfolio data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.am.portfolio.client.parser.api;

import com.am.portfolio.client.parser.invoker.ApiClient;
import com.am.portfolio.client.parser.invoker.ApiException;
import com.am.portfolio.client.parser.invoker.ApiResponse;
import com.am.portfolio.client.parser.invoker.Configuration;
import com.am.portfolio.client.parser.invoker.Pair;

import java.io.File;
import com.am.portfolio.client.parser.model.HTTPValidationError;
import com.am.portfolio.client.parser.model.JobResponse;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import org.apache.http.HttpEntity;
import org.apache.http.NameValuePair;
import org.apache.http.entity.mime.MultipartEntityBuilder;
import org.apache.http.message.BasicNameValuePair;
import org.apache.http.client.entity.UrlEncodedFormEntity;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-27T02:38:35.395601500+05:30[Asia/Calcutta]", comments = "Generator version: 7.18.0")
public class EtfHoldingsApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public EtfHoldingsApi() {
    this(Configuration.getDefaultApiClient());
  }

  public EtfHoldingsApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Fetch All Etf Holdings
   * Fetch holdings for all ETFs with ISINs from moneycontrol API Returns immediately with job ID, processes in background Smart caching: Only fetches if data is missing or stale
   * @param callbackUrl  (optional)
   * @param userId  (optional)
   * @param limit Limit number of ETFs to process (optional)
   * @param forceRefresh Force refresh even if data exists for today (optional, default to false)
   * @return JobResponse
   * @throws ApiException if fails to make API call
   */
  public JobResponse fetchAllEtfHoldingsV1FetchAllHoldingsPost(@javax.annotation.Nullable String callbackUrl, @javax.annotation.Nullable String userId, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Boolean forceRefresh) throws ApiException {
    return fetchAllEtfHoldingsV1FetchAllHoldingsPost(callbackUrl, userId, limit, forceRefresh, null);
  }

  /**
   * Fetch All Etf Holdings
   * Fetch holdings for all ETFs with ISINs from moneycontrol API Returns immediately with job ID, processes in background Smart caching: Only fetches if data is missing or stale
   * @param callbackUrl  (optional)
   * @param userId  (optional)
   * @param limit Limit number of ETFs to process (optional)
   * @param forceRefresh Force refresh even if data exists for today (optional, default to false)
   * @param headers Optional headers to include in the request
   * @return JobResponse
   * @throws ApiException if fails to make API call
   */
  public JobResponse fetchAllEtfHoldingsV1FetchAllHoldingsPost(@javax.annotation.Nullable String callbackUrl, @javax.annotation.Nullable String userId, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Boolean forceRefresh, Map<String, String> headers) throws ApiException {
    ApiResponse<JobResponse> localVarResponse = fetchAllEtfHoldingsV1FetchAllHoldingsPostWithHttpInfo(callbackUrl, userId, limit, forceRefresh, headers);
    return localVarResponse.getData();
  }

  /**
   * Fetch All Etf Holdings
   * Fetch holdings for all ETFs with ISINs from moneycontrol API Returns immediately with job ID, processes in background Smart caching: Only fetches if data is missing or stale
   * @param callbackUrl  (optional)
   * @param userId  (optional)
   * @param limit Limit number of ETFs to process (optional)
   * @param forceRefresh Force refresh even if data exists for today (optional, default to false)
   * @return ApiResponse&lt;JobResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<JobResponse> fetchAllEtfHoldingsV1FetchAllHoldingsPostWithHttpInfo(@javax.annotation.Nullable String callbackUrl, @javax.annotation.Nullable String userId, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Boolean forceRefresh) throws ApiException {
    return fetchAllEtfHoldingsV1FetchAllHoldingsPostWithHttpInfo(callbackUrl, userId, limit, forceRefresh, null);
  }

  /**
   * Fetch All Etf Holdings
   * Fetch holdings for all ETFs with ISINs from moneycontrol API Returns immediately with job ID, processes in background Smart caching: Only fetches if data is missing or stale
   * @param callbackUrl  (optional)
   * @param userId  (optional)
   * @param limit Limit number of ETFs to process (optional)
   * @param forceRefresh Force refresh even if data exists for today (optional, default to false)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;JobResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<JobResponse> fetchAllEtfHoldingsV1FetchAllHoldingsPostWithHttpInfo(@javax.annotation.Nullable String callbackUrl, @javax.annotation.Nullable String userId, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Boolean forceRefresh, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = fetchAllEtfHoldingsV1FetchAllHoldingsPostRequestBuilder(callbackUrl, userId, limit, forceRefresh, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("fetchAllEtfHoldingsV1FetchAllHoldingsPost", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<JobResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        JobResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<JobResponse>() {});
        

        return new ApiResponse<JobResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder fetchAllEtfHoldingsV1FetchAllHoldingsPostRequestBuilder(@javax.annotation.Nullable String callbackUrl, @javax.annotation.Nullable String userId, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Boolean forceRefresh, Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/fetch-all-holdings";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "callback_url";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("callback_url", callbackUrl));
    localVarQueryParameterBaseName = "user_id";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("user_id", userId));
    localVarQueryParameterBaseName = "limit";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("limit", limit));
    localVarQueryParameterBaseName = "force_refresh";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("force_refresh", forceRefresh));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Fetch Holdings For Etf
   * Fetch holdings for a specific ETF by symbol Returns immediately with job ID, processes in background
   * @param symbol  (required)
   * @param callbackUrl  (optional)
   * @param userId  (optional)
   * @return Object
   * @throws ApiException if fails to make API call
   */
  public Object fetchHoldingsForEtfV1FetchHoldingsSymbolPost(@javax.annotation.Nonnull String symbol, @javax.annotation.Nullable String callbackUrl, @javax.annotation.Nullable String userId) throws ApiException {
    return fetchHoldingsForEtfV1FetchHoldingsSymbolPost(symbol, callbackUrl, userId, null);
  }

  /**
   * Fetch Holdings For Etf
   * Fetch holdings for a specific ETF by symbol Returns immediately with job ID, processes in background
   * @param symbol  (required)
   * @param callbackUrl  (optional)
   * @param userId  (optional)
   * @param headers Optional headers to include in the request
   * @return Object
   * @throws ApiException if fails to make API call
   */
  public Object fetchHoldingsForEtfV1FetchHoldingsSymbolPost(@javax.annotation.Nonnull String symbol, @javax.annotation.Nullable String callbackUrl, @javax.annotation.Nullable String userId, Map<String, String> headers) throws ApiException {
    ApiResponse<Object> localVarResponse = fetchHoldingsForEtfV1FetchHoldingsSymbolPostWithHttpInfo(symbol, callbackUrl, userId, headers);
    return localVarResponse.getData();
  }

  /**
   * Fetch Holdings For Etf
   * Fetch holdings for a specific ETF by symbol Returns immediately with job ID, processes in background
   * @param symbol  (required)
   * @param callbackUrl  (optional)
   * @param userId  (optional)
   * @return ApiResponse&lt;Object&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Object> fetchHoldingsForEtfV1FetchHoldingsSymbolPostWithHttpInfo(@javax.annotation.Nonnull String symbol, @javax.annotation.Nullable String callbackUrl, @javax.annotation.Nullable String userId) throws ApiException {
    return fetchHoldingsForEtfV1FetchHoldingsSymbolPostWithHttpInfo(symbol, callbackUrl, userId, null);
  }

  /**
   * Fetch Holdings For Etf
   * Fetch holdings for a specific ETF by symbol Returns immediately with job ID, processes in background
   * @param symbol  (required)
   * @param callbackUrl  (optional)
   * @param userId  (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Object&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Object> fetchHoldingsForEtfV1FetchHoldingsSymbolPostWithHttpInfo(@javax.annotation.Nonnull String symbol, @javax.annotation.Nullable String callbackUrl, @javax.annotation.Nullable String userId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = fetchHoldingsForEtfV1FetchHoldingsSymbolPostRequestBuilder(symbol, callbackUrl, userId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("fetchHoldingsForEtfV1FetchHoldingsSymbolPost", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<Object>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        Object responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<Object>() {});
        

        return new ApiResponse<Object>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder fetchHoldingsForEtfV1FetchHoldingsSymbolPostRequestBuilder(@javax.annotation.Nonnull String symbol, @javax.annotation.Nullable String callbackUrl, @javax.annotation.Nullable String userId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'symbol' is set
    if (symbol == null) {
      throw new ApiException(400, "Missing the required parameter 'symbol' when calling fetchHoldingsForEtfV1FetchHoldingsSymbolPost");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/fetch-holdings/{symbol}"
        .replace("{symbol}", ApiClient.urlEncode(symbol.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "callback_url";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("callback_url", callbackUrl));
    localVarQueryParameterBaseName = "user_id";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("user_id", userId));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get Cache Statistics
   * Get ETF holdings cache statistics
   * @return Object
   * @throws ApiException if fails to make API call
   */
  public Object getCacheStatisticsV1CacheStatsGet() throws ApiException {
    return getCacheStatisticsV1CacheStatsGet(null);
  }

  /**
   * Get Cache Statistics
   * Get ETF holdings cache statistics
   * @param headers Optional headers to include in the request
   * @return Object
   * @throws ApiException if fails to make API call
   */
  public Object getCacheStatisticsV1CacheStatsGet(Map<String, String> headers) throws ApiException {
    ApiResponse<Object> localVarResponse = getCacheStatisticsV1CacheStatsGetWithHttpInfo(headers);
    return localVarResponse.getData();
  }

  /**
   * Get Cache Statistics
   * Get ETF holdings cache statistics
   * @return ApiResponse&lt;Object&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Object> getCacheStatisticsV1CacheStatsGetWithHttpInfo() throws ApiException {
    return getCacheStatisticsV1CacheStatsGetWithHttpInfo(null);
  }

  /**
   * Get Cache Statistics
   * Get ETF holdings cache statistics
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Object&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Object> getCacheStatisticsV1CacheStatsGetWithHttpInfo(Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getCacheStatisticsV1CacheStatsGetRequestBuilder(headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getCacheStatisticsV1CacheStatsGet", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<Object>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        Object responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<Object>() {});
        

        return new ApiResponse<Object>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getCacheStatisticsV1CacheStatsGetRequestBuilder(Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/cache-stats";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get Etf Holdings
   * Get stored holdings for a specific ETF
   * @param symbol  (required)
   * @return Object
   * @throws ApiException if fails to make API call
   */
  public Object getEtfHoldingsV1HoldingsSymbolGet(@javax.annotation.Nonnull String symbol) throws ApiException {
    return getEtfHoldingsV1HoldingsSymbolGet(symbol, null);
  }

  /**
   * Get Etf Holdings
   * Get stored holdings for a specific ETF
   * @param symbol  (required)
   * @param headers Optional headers to include in the request
   * @return Object
   * @throws ApiException if fails to make API call
   */
  public Object getEtfHoldingsV1HoldingsSymbolGet(@javax.annotation.Nonnull String symbol, Map<String, String> headers) throws ApiException {
    ApiResponse<Object> localVarResponse = getEtfHoldingsV1HoldingsSymbolGetWithHttpInfo(symbol, headers);
    return localVarResponse.getData();
  }

  /**
   * Get Etf Holdings
   * Get stored holdings for a specific ETF
   * @param symbol  (required)
   * @return ApiResponse&lt;Object&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Object> getEtfHoldingsV1HoldingsSymbolGetWithHttpInfo(@javax.annotation.Nonnull String symbol) throws ApiException {
    return getEtfHoldingsV1HoldingsSymbolGetWithHttpInfo(symbol, null);
  }

  /**
   * Get Etf Holdings
   * Get stored holdings for a specific ETF
   * @param symbol  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Object&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Object> getEtfHoldingsV1HoldingsSymbolGetWithHttpInfo(@javax.annotation.Nonnull String symbol, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getEtfHoldingsV1HoldingsSymbolGetRequestBuilder(symbol, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getEtfHoldingsV1HoldingsSymbolGet", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<Object>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        Object responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<Object>() {});
        

        return new ApiResponse<Object>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getEtfHoldingsV1HoldingsSymbolGetRequestBuilder(@javax.annotation.Nonnull String symbol, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'symbol' is set
    if (symbol == null) {
      throw new ApiException(400, "Missing the required parameter 'symbol' when calling getEtfHoldingsV1HoldingsSymbolGet");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/holdings/{symbol}"
        .replace("{symbol}", ApiClient.urlEncode(symbol.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get Etf Stats
   * Get ETF database statistics
   * @return Object
   * @throws ApiException if fails to make API call
   */
  public Object getEtfStatsV1StatsGet() throws ApiException {
    return getEtfStatsV1StatsGet(null);
  }

  /**
   * Get Etf Stats
   * Get ETF database statistics
   * @param headers Optional headers to include in the request
   * @return Object
   * @throws ApiException if fails to make API call
   */
  public Object getEtfStatsV1StatsGet(Map<String, String> headers) throws ApiException {
    ApiResponse<Object> localVarResponse = getEtfStatsV1StatsGetWithHttpInfo(headers);
    return localVarResponse.getData();
  }

  /**
   * Get Etf Stats
   * Get ETF database statistics
   * @return ApiResponse&lt;Object&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Object> getEtfStatsV1StatsGetWithHttpInfo() throws ApiException {
    return getEtfStatsV1StatsGetWithHttpInfo(null);
  }

  /**
   * Get Etf Stats
   * Get ETF database statistics
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Object&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Object> getEtfStatsV1StatsGetWithHttpInfo(Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getEtfStatsV1StatsGetRequestBuilder(headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getEtfStatsV1StatsGet", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<Object>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        Object responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<Object>() {});
        

        return new ApiResponse<Object>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getEtfStatsV1StatsGetRequestBuilder(Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/stats";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Load Etfs From Json
   * Load ETF data from JSON file Accepts etf_details.json and loads all ETFs into database
   * @param _file ETF details JSON file (required)
   * @param dryRun Validate only, don&#39;t persist (optional, default to false)
   * @return Object
   * @throws ApiException if fails to make API call
   */
  public Object loadEtfsFromJsonV1LoadFromJsonPost(@javax.annotation.Nonnull File _file, @javax.annotation.Nullable Boolean dryRun) throws ApiException {
    return loadEtfsFromJsonV1LoadFromJsonPost(_file, dryRun, null);
  }

  /**
   * Load Etfs From Json
   * Load ETF data from JSON file Accepts etf_details.json and loads all ETFs into database
   * @param _file ETF details JSON file (required)
   * @param dryRun Validate only, don&#39;t persist (optional, default to false)
   * @param headers Optional headers to include in the request
   * @return Object
   * @throws ApiException if fails to make API call
   */
  public Object loadEtfsFromJsonV1LoadFromJsonPost(@javax.annotation.Nonnull File _file, @javax.annotation.Nullable Boolean dryRun, Map<String, String> headers) throws ApiException {
    ApiResponse<Object> localVarResponse = loadEtfsFromJsonV1LoadFromJsonPostWithHttpInfo(_file, dryRun, headers);
    return localVarResponse.getData();
  }

  /**
   * Load Etfs From Json
   * Load ETF data from JSON file Accepts etf_details.json and loads all ETFs into database
   * @param _file ETF details JSON file (required)
   * @param dryRun Validate only, don&#39;t persist (optional, default to false)
   * @return ApiResponse&lt;Object&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Object> loadEtfsFromJsonV1LoadFromJsonPostWithHttpInfo(@javax.annotation.Nonnull File _file, @javax.annotation.Nullable Boolean dryRun) throws ApiException {
    return loadEtfsFromJsonV1LoadFromJsonPostWithHttpInfo(_file, dryRun, null);
  }

  /**
   * Load Etfs From Json
   * Load ETF data from JSON file Accepts etf_details.json and loads all ETFs into database
   * @param _file ETF details JSON file (required)
   * @param dryRun Validate only, don&#39;t persist (optional, default to false)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Object&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Object> loadEtfsFromJsonV1LoadFromJsonPostWithHttpInfo(@javax.annotation.Nonnull File _file, @javax.annotation.Nullable Boolean dryRun, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = loadEtfsFromJsonV1LoadFromJsonPostRequestBuilder(_file, dryRun, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("loadEtfsFromJsonV1LoadFromJsonPost", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<Object>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        Object responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<Object>() {});
        

        return new ApiResponse<Object>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder loadEtfsFromJsonV1LoadFromJsonPostRequestBuilder(@javax.annotation.Nonnull File _file, @javax.annotation.Nullable Boolean dryRun, Map<String, String> headers) throws ApiException {
    // verify the required parameter '_file' is set
    if (_file == null) {
      throw new ApiException(400, "Missing the required parameter '_file' when calling loadEtfsFromJsonV1LoadFromJsonPost");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/load-from-json";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "dry_run";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("dry_run", dryRun));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    MultipartEntityBuilder multiPartBuilder = MultipartEntityBuilder.create();
    boolean hasFiles = false;
    multiPartBuilder.addBinaryBody("file", _file);
    hasFiles = true;
    HttpEntity entity = multiPartBuilder.build();
    HttpRequest.BodyPublisher formDataPublisher;
    if (hasFiles) {
        Pipe pipe;
        try {
            pipe = Pipe.open();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        new Thread(() -> {
            try (OutputStream outputStream = Channels.newOutputStream(pipe.sink())) {
                entity.writeTo(outputStream);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }).start();
        formDataPublisher = HttpRequest.BodyPublishers.ofInputStream(() -> Channels.newInputStream(pipe.source()));
    } else {
        ByteArrayOutputStream formOutputStream = new ByteArrayOutputStream();
        try {
            entity.writeTo(formOutputStream);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        byte[] formBytes = formOutputStream.toByteArray();
        formDataPublisher = HttpRequest.BodyPublishers
            .ofInputStream(() -> new ByteArrayInputStream(formBytes));
    }
    localVarRequestBuilder
        .header("Content-Type", entity.getContentType().getValue())
        .method("POST", formDataPublisher);
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Search Etfs
   * Search ETFs by symbol, name, or ISIN
   * @param query Search by symbol, name, or ISIN (required)
   * @param limit Maximum results to return (optional, default to 10)
   * @return Object
   * @throws ApiException if fails to make API call
   */
  public Object searchEtfsV1SearchGet(@javax.annotation.Nonnull String query, @javax.annotation.Nullable Integer limit) throws ApiException {
    return searchEtfsV1SearchGet(query, limit, null);
  }

  /**
   * Search Etfs
   * Search ETFs by symbol, name, or ISIN
   * @param query Search by symbol, name, or ISIN (required)
   * @param limit Maximum results to return (optional, default to 10)
   * @param headers Optional headers to include in the request
   * @return Object
   * @throws ApiException if fails to make API call
   */
  public Object searchEtfsV1SearchGet(@javax.annotation.Nonnull String query, @javax.annotation.Nullable Integer limit, Map<String, String> headers) throws ApiException {
    ApiResponse<Object> localVarResponse = searchEtfsV1SearchGetWithHttpInfo(query, limit, headers);
    return localVarResponse.getData();
  }

  /**
   * Search Etfs
   * Search ETFs by symbol, name, or ISIN
   * @param query Search by symbol, name, or ISIN (required)
   * @param limit Maximum results to return (optional, default to 10)
   * @return ApiResponse&lt;Object&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Object> searchEtfsV1SearchGetWithHttpInfo(@javax.annotation.Nonnull String query, @javax.annotation.Nullable Integer limit) throws ApiException {
    return searchEtfsV1SearchGetWithHttpInfo(query, limit, null);
  }

  /**
   * Search Etfs
   * Search ETFs by symbol, name, or ISIN
   * @param query Search by symbol, name, or ISIN (required)
   * @param limit Maximum results to return (optional, default to 10)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Object&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Object> searchEtfsV1SearchGetWithHttpInfo(@javax.annotation.Nonnull String query, @javax.annotation.Nullable Integer limit, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = searchEtfsV1SearchGetRequestBuilder(query, limit, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("searchEtfsV1SearchGet", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<Object>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        Object responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<Object>() {});
        

        return new ApiResponse<Object>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder searchEtfsV1SearchGetRequestBuilder(@javax.annotation.Nonnull String query, @javax.annotation.Nullable Integer limit, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'query' is set
    if (query == null) {
      throw new ApiException(400, "Missing the required parameter 'query' when calling searchEtfsV1SearchGet");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/search";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "query";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("query", query));
    localVarQueryParameterBaseName = "limit";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("limit", limit));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
