# coding: utf-8

"""
    Market Data API Documentation

    API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.

    The version of the OpenAPI document: 1.0.0
    Contact: support@amportfolio.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from am_market_client.models.security_metadata import SecurityMetadata

class TestSecurityMetadata(unittest.TestCase):
    """SecurityMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SecurityMetadata:
        """Test SecurityMetadata
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SecurityMetadata`
        """
        model = SecurityMetadata()
        if include_optional:
            return SecurityMetadata(
                sector = '',
                industry = '',
                market_cap_value = 56,
                market_cap_type = ''
            )
        else:
            return SecurityMetadata(
        )
        """

    def testSecurityMetadata(self):
        """Test SecurityMetadata"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
