# coding: utf-8

"""
    Market Data API Documentation

    API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.

    The version of the OpenAPI document: 1.0.0
    Contact: support@amportfolio.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from am_market_client.api.margin_calculator_api import MarginCalculatorApi


class TestMarginCalculatorApi(unittest.TestCase):
    """MarginCalculatorApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MarginCalculatorApi()

    def tearDown(self) -> None:
        pass

    def test_calculate_margin(self) -> None:
        """Test case for calculate_margin

        Calculate margin requirements
        """
        pass

    def test_calculate_margin_async(self) -> None:
        """Test case for calculate_margin_async

        Calculate margin requirements asynchronously
        """
        pass


if __name__ == '__main__':
    unittest.main()
