# coding: utf-8

"""
    Market Data API Documentation

    API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.

    The version of the OpenAPI document: 1.0.0
    Contact: support@amportfolio.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from am_market_client.api.security_explorer_api import SecurityExplorerApi


class TestSecurityExplorerApi(unittest.TestCase):
    """SecurityExplorerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SecurityExplorerApi()

    def tearDown(self) -> None:
        pass

    def test_search(self) -> None:
        """Test case for search

        Search securities by symbol or ISIN
        """
        pass

    def test_search_advanced(self) -> None:
        """Test case for search_advanced

        Advanced search securities with filters
        """
        pass


if __name__ == '__main__':
    unittest.main()
