# coding: utf-8

"""
    Market Data API Documentation

    API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.

    The version of the OpenAPI document: 1.0.0
    Contact: support@amportfolio.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from am_market_client.models.brokerage_calculation_request import BrokerageCalculationRequest

class TestBrokerageCalculationRequest(unittest.TestCase):
    """BrokerageCalculationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BrokerageCalculationRequest:
        """Test BrokerageCalculationRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BrokerageCalculationRequest`
        """
        model = BrokerageCalculationRequest()
        if include_optional:
            return BrokerageCalculationRequest(
                trading_symbol = '',
                quantity = 56,
                buy_price = 1.337,
                sell_price = 1.337,
                exchange = '',
                trade_type = 'DELIVERY',
                broker_type = 'DISCOUNT',
                broker_name = '',
                broker_flat_fee = 1.337,
                broker_percentage_fee = 1.337,
                state_code = ''
            )
        else:
            return BrokerageCalculationRequest(
        )
        """

    def testBrokerageCalculationRequest(self):
        """Test BrokerageCalculationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
