# coding: utf-8

"""
    Market Data API Documentation

    API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.

    The version of the OpenAPI document: 1.0.0
    Contact: support@amportfolio.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from am_market_client.models.historical_data_metadata import HistoricalDataMetadata

class TestHistoricalDataMetadata(unittest.TestCase):
    """HistoricalDataMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HistoricalDataMetadata:
        """Test HistoricalDataMetadata
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HistoricalDataMetadata`
        """
        model = HistoricalDataMetadata()
        if include_optional:
            return HistoricalDataMetadata(
                from_date = '',
                to_date = '',
                interval = '',
                interval_enum = '',
                total_symbols = 56,
                successful_symbols = 56,
                total_data_points = 56,
                filtered_data_points = 56,
                filtered = True,
                filter_type = '',
                filter_frequency = 56,
                processing_time_ms = 56,
                source = ''
            )
        else:
            return HistoricalDataMetadata(
        )
        """

    def testHistoricalDataMetadata(self):
        """Test HistoricalDataMetadata"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
