/*
 * Mutual Fund Portfolio API
 * REST API for managing mutual fund portfolio data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.parser.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.am.portfolio.client.parser.model.JobStatus;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.portfolio.client.parser.invoker.ApiClient;
/**
 * API response for job creation
 */
@JsonPropertyOrder({
  JobResponse.JSON_PROPERTY_JOB_ID,
  JobResponse.JSON_PROPERTY_STATUS,
  JobResponse.JSON_PROPERTY_MESSAGE,
  JobResponse.JSON_PROPERTY_ESTIMATED_COMPLETION_TIME,
  JobResponse.JSON_PROPERTY_STATUS_URL,
  JobResponse.JSON_PROPERTY_WEBHOOK_URL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-27T09:34:32.125497100+05:30[Asia/Calcutta]", comments = "Generator version: 7.18.0")
public class JobResponse {
  public static final String JSON_PROPERTY_JOB_ID = "job_id";
  @javax.annotation.Nonnull
  private String jobId;

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nonnull
  private JobStatus status;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  @javax.annotation.Nonnull
  private String message;

  public static final String JSON_PROPERTY_ESTIMATED_COMPLETION_TIME = "estimated_completion_time";
  private JsonNullable<String> estimatedCompletionTime = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_STATUS_URL = "status_url";
  @javax.annotation.Nonnull
  private String statusUrl;

  public static final String JSON_PROPERTY_WEBHOOK_URL = "webhook_url";
  private JsonNullable<String> webhookUrl = JsonNullable.<String>undefined();

  public JobResponse() { 
  }

  public JobResponse jobId(@javax.annotation.Nonnull String jobId) {
    this.jobId = jobId;
    return this;
  }

  /**
   * Get jobId
   * @return jobId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_JOB_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getJobId() {
    return jobId;
  }


  @JsonProperty(value = JSON_PROPERTY_JOB_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setJobId(@javax.annotation.Nonnull String jobId) {
    this.jobId = jobId;
  }


  public JobResponse status(@javax.annotation.Nonnull JobStatus status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public JobStatus getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@javax.annotation.Nonnull JobStatus status) {
    this.status = status;
  }


  public JobResponse message(@javax.annotation.Nonnull String message) {
    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getMessage() {
    return message;
  }


  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessage(@javax.annotation.Nonnull String message) {
    this.message = message;
  }


  public JobResponse estimatedCompletionTime(@javax.annotation.Nullable String estimatedCompletionTime) {
    this.estimatedCompletionTime = JsonNullable.<String>of(estimatedCompletionTime);
    return this;
  }

  /**
   * Get estimatedCompletionTime
   * @return estimatedCompletionTime
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getEstimatedCompletionTime() {
        return estimatedCompletionTime.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_ESTIMATED_COMPLETION_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getEstimatedCompletionTime_JsonNullable() {
    return estimatedCompletionTime;
  }
  
  @JsonProperty(JSON_PROPERTY_ESTIMATED_COMPLETION_TIME)
  public void setEstimatedCompletionTime_JsonNullable(JsonNullable<String> estimatedCompletionTime) {
    this.estimatedCompletionTime = estimatedCompletionTime;
  }

  public void setEstimatedCompletionTime(@javax.annotation.Nullable String estimatedCompletionTime) {
    this.estimatedCompletionTime = JsonNullable.<String>of(estimatedCompletionTime);
  }


  public JobResponse statusUrl(@javax.annotation.Nonnull String statusUrl) {
    this.statusUrl = statusUrl;
    return this;
  }

  /**
   * Get statusUrl
   * @return statusUrl
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATUS_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getStatusUrl() {
    return statusUrl;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatusUrl(@javax.annotation.Nonnull String statusUrl) {
    this.statusUrl = statusUrl;
  }


  public JobResponse webhookUrl(@javax.annotation.Nullable String webhookUrl) {
    this.webhookUrl = JsonNullable.<String>of(webhookUrl);
    return this;
  }

  /**
   * Get webhookUrl
   * @return webhookUrl
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getWebhookUrl() {
        return webhookUrl.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_WEBHOOK_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getWebhookUrl_JsonNullable() {
    return webhookUrl;
  }
  
  @JsonProperty(JSON_PROPERTY_WEBHOOK_URL)
  public void setWebhookUrl_JsonNullable(JsonNullable<String> webhookUrl) {
    this.webhookUrl = webhookUrl;
  }

  public void setWebhookUrl(@javax.annotation.Nullable String webhookUrl) {
    this.webhookUrl = JsonNullable.<String>of(webhookUrl);
  }


  /**
   * Return true if this JobResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JobResponse jobResponse = (JobResponse) o;
    return Objects.equals(this.jobId, jobResponse.jobId) &&
        Objects.equals(this.status, jobResponse.status) &&
        Objects.equals(this.message, jobResponse.message) &&
        equalsNullable(this.estimatedCompletionTime, jobResponse.estimatedCompletionTime) &&
        Objects.equals(this.statusUrl, jobResponse.statusUrl) &&
        equalsNullable(this.webhookUrl, jobResponse.webhookUrl);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(jobId, status, message, hashCodeNullable(estimatedCompletionTime), statusUrl, hashCodeNullable(webhookUrl));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobResponse {\n");
    sb.append("    jobId: ").append(toIndentedString(jobId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    estimatedCompletionTime: ").append(toIndentedString(estimatedCompletionTime)).append("\n");
    sb.append("    statusUrl: ").append(toIndentedString(statusUrl)).append("\n");
    sb.append("    webhookUrl: ").append(toIndentedString(webhookUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `job_id` to the URL query string
    if (getJobId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sjob_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getJobId()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `message` to the URL query string
    if (getMessage() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smessage%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMessage()))));
    }

    // add `estimated_completion_time` to the URL query string
    if (getEstimatedCompletionTime() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sestimated_completion_time%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEstimatedCompletionTime()))));
    }

    // add `status_url` to the URL query string
    if (getStatusUrl() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatus_url%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatusUrl()))));
    }

    // add `webhook_url` to the URL query string
    if (getWebhookUrl() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%swebhook_url%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWebhookUrl()))));
    }

    return joiner.toString();
  }
}

