/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.market.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.portfolio.client.market.invoker.ApiClient;
/**
 * CookieInfo
 */
@JsonPropertyOrder({
  CookieInfo.JSON_PROPERTY_NAME,
  CookieInfo.JSON_PROPERTY_VALUE,
  CookieInfo.JSON_PROPERTY_DOMAIN,
  CookieInfo.JSON_PROPERTY_PATH,
  CookieInfo.JSON_PROPERTY_SECURE,
  CookieInfo.JSON_PROPERTY_HTTP_ONLY,
  CookieInfo.JSON_PROPERTY_SAME_SITE,
  CookieInfo.JSON_PROPERTY_EXPIRY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-27T02:38:11.838038900+05:30[Asia/Calcutta]", comments = "Generator version: 7.18.0")
public class CookieInfo {
  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_VALUE = "value";
  @javax.annotation.Nullable
  private String value;

  public static final String JSON_PROPERTY_DOMAIN = "domain";
  @javax.annotation.Nullable
  private String domain;

  public static final String JSON_PROPERTY_PATH = "path";
  @javax.annotation.Nullable
  private String path;

  public static final String JSON_PROPERTY_SECURE = "secure";
  @javax.annotation.Nullable
  private Boolean secure;

  public static final String JSON_PROPERTY_HTTP_ONLY = "httpOnly";
  @javax.annotation.Nullable
  private Boolean httpOnly;

  public static final String JSON_PROPERTY_SAME_SITE = "sameSite";
  @javax.annotation.Nullable
  private String sameSite;

  public static final String JSON_PROPERTY_EXPIRY = "expiry";
  @javax.annotation.Nullable
  private Long expiry;

  public CookieInfo() { 
  }

  public CookieInfo name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public CookieInfo value(@javax.annotation.Nullable String value) {
    this.value = value;
    return this;
  }

  /**
   * Get value
   * @return value
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getValue() {
    return value;
  }


  @JsonProperty(value = JSON_PROPERTY_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValue(@javax.annotation.Nullable String value) {
    this.value = value;
  }


  public CookieInfo domain(@javax.annotation.Nullable String domain) {
    this.domain = domain;
    return this;
  }

  /**
   * Get domain
   * @return domain
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DOMAIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDomain() {
    return domain;
  }


  @JsonProperty(value = JSON_PROPERTY_DOMAIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDomain(@javax.annotation.Nullable String domain) {
    this.domain = domain;
  }


  public CookieInfo path(@javax.annotation.Nullable String path) {
    this.path = path;
    return this;
  }

  /**
   * Get path
   * @return path
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PATH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPath() {
    return path;
  }


  @JsonProperty(value = JSON_PROPERTY_PATH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPath(@javax.annotation.Nullable String path) {
    this.path = path;
  }


  public CookieInfo secure(@javax.annotation.Nullable Boolean secure) {
    this.secure = secure;
    return this;
  }

  /**
   * Get secure
   * @return secure
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SECURE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getSecure() {
    return secure;
  }


  @JsonProperty(value = JSON_PROPERTY_SECURE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSecure(@javax.annotation.Nullable Boolean secure) {
    this.secure = secure;
  }


  public CookieInfo httpOnly(@javax.annotation.Nullable Boolean httpOnly) {
    this.httpOnly = httpOnly;
    return this;
  }

  /**
   * Get httpOnly
   * @return httpOnly
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HTTP_ONLY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getHttpOnly() {
    return httpOnly;
  }


  @JsonProperty(value = JSON_PROPERTY_HTTP_ONLY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHttpOnly(@javax.annotation.Nullable Boolean httpOnly) {
    this.httpOnly = httpOnly;
  }


  public CookieInfo sameSite(@javax.annotation.Nullable String sameSite) {
    this.sameSite = sameSite;
    return this;
  }

  /**
   * Get sameSite
   * @return sameSite
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SAME_SITE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSameSite() {
    return sameSite;
  }


  @JsonProperty(value = JSON_PROPERTY_SAME_SITE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSameSite(@javax.annotation.Nullable String sameSite) {
    this.sameSite = sameSite;
  }


  public CookieInfo expiry(@javax.annotation.Nullable Long expiry) {
    this.expiry = expiry;
    return this;
  }

  /**
   * Get expiry
   * @return expiry
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXPIRY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getExpiry() {
    return expiry;
  }


  @JsonProperty(value = JSON_PROPERTY_EXPIRY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpiry(@javax.annotation.Nullable Long expiry) {
    this.expiry = expiry;
  }


  /**
   * Return true if this CookieInfo object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CookieInfo cookieInfo = (CookieInfo) o;
    return Objects.equals(this.name, cookieInfo.name) &&
        Objects.equals(this.value, cookieInfo.value) &&
        Objects.equals(this.domain, cookieInfo.domain) &&
        Objects.equals(this.path, cookieInfo.path) &&
        Objects.equals(this.secure, cookieInfo.secure) &&
        Objects.equals(this.httpOnly, cookieInfo.httpOnly) &&
        Objects.equals(this.sameSite, cookieInfo.sameSite) &&
        Objects.equals(this.expiry, cookieInfo.expiry);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, value, domain, path, secure, httpOnly, sameSite, expiry);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CookieInfo {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    domain: ").append(toIndentedString(domain)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    secure: ").append(toIndentedString(secure)).append("\n");
    sb.append("    httpOnly: ").append(toIndentedString(httpOnly)).append("\n");
    sb.append("    sameSite: ").append(toIndentedString(sameSite)).append("\n");
    sb.append("    expiry: ").append(toIndentedString(expiry)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `value` to the URL query string
    if (getValue() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%svalue%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getValue()))));
    }

    // add `domain` to the URL query string
    if (getDomain() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdomain%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDomain()))));
    }

    // add `path` to the URL query string
    if (getPath() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spath%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPath()))));
    }

    // add `secure` to the URL query string
    if (getSecure() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssecure%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSecure()))));
    }

    // add `httpOnly` to the URL query string
    if (getHttpOnly() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%shttpOnly%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHttpOnly()))));
    }

    // add `sameSite` to the URL query string
    if (getSameSite() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssameSite%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSameSite()))));
    }

    // add `expiry` to the URL query string
    if (getExpiry() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sexpiry%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExpiry()))));
    }

    return joiner.toString();
  }
}

