/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.market.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.portfolio.client.market.invoker.ApiClient;
/**
 * InstrumentSearchCriteria
 */
@JsonPropertyOrder({
  InstrumentSearchCriteria.JSON_PROPERTY_QUERIES,
  InstrumentSearchCriteria.JSON_PROPERTY_EXCHANGES,
  InstrumentSearchCriteria.JSON_PROPERTY_INSTRUMENT_TYPES,
  InstrumentSearchCriteria.JSON_PROPERTY_SEGMENTS,
  InstrumentSearchCriteria.JSON_PROPERTY_ISINS,
  InstrumentSearchCriteria.JSON_PROPERTY_TRADING_SYMBOLS,
  InstrumentSearchCriteria.JSON_PROPERTY_WEEKLY,
  InstrumentSearchCriteria.JSON_PROPERTY_PROVIDER
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-27T01:58:01.787863300+05:30[Asia/Calcutta]", comments = "Generator version: 7.18.0")
public class InstrumentSearchCriteria {
  public static final String JSON_PROPERTY_QUERIES = "queries";
  @javax.annotation.Nullable
  private List<String> queries = new ArrayList<>();

  public static final String JSON_PROPERTY_EXCHANGES = "exchanges";
  @javax.annotation.Nullable
  private List<String> exchanges = new ArrayList<>();

  public static final String JSON_PROPERTY_INSTRUMENT_TYPES = "instrumentTypes";
  @javax.annotation.Nullable
  private List<String> instrumentTypes = new ArrayList<>();

  public static final String JSON_PROPERTY_SEGMENTS = "segments";
  @javax.annotation.Nullable
  private List<String> segments = new ArrayList<>();

  public static final String JSON_PROPERTY_ISINS = "isins";
  @javax.annotation.Nullable
  private List<String> isins = new ArrayList<>();

  public static final String JSON_PROPERTY_TRADING_SYMBOLS = "tradingSymbols";
  @javax.annotation.Nullable
  private List<String> tradingSymbols = new ArrayList<>();

  public static final String JSON_PROPERTY_WEEKLY = "weekly";
  @javax.annotation.Nullable
  private Boolean weekly;

  public static final String JSON_PROPERTY_PROVIDER = "provider";
  @javax.annotation.Nullable
  private String provider;

  public InstrumentSearchCriteria() { 
  }

  public InstrumentSearchCriteria queries(@javax.annotation.Nullable List<String> queries) {
    this.queries = queries;
    return this;
  }

  public InstrumentSearchCriteria addQueriesItem(String queriesItem) {
    if (this.queries == null) {
      this.queries = new ArrayList<>();
    }
    this.queries.add(queriesItem);
    return this;
  }

  /**
   * Get queries
   * @return queries
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_QUERIES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getQueries() {
    return queries;
  }


  @JsonProperty(value = JSON_PROPERTY_QUERIES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQueries(@javax.annotation.Nullable List<String> queries) {
    this.queries = queries;
  }


  public InstrumentSearchCriteria exchanges(@javax.annotation.Nullable List<String> exchanges) {
    this.exchanges = exchanges;
    return this;
  }

  public InstrumentSearchCriteria addExchangesItem(String exchangesItem) {
    if (this.exchanges == null) {
      this.exchanges = new ArrayList<>();
    }
    this.exchanges.add(exchangesItem);
    return this;
  }

  /**
   * Get exchanges
   * @return exchanges
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXCHANGES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getExchanges() {
    return exchanges;
  }


  @JsonProperty(value = JSON_PROPERTY_EXCHANGES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExchanges(@javax.annotation.Nullable List<String> exchanges) {
    this.exchanges = exchanges;
  }


  public InstrumentSearchCriteria instrumentTypes(@javax.annotation.Nullable List<String> instrumentTypes) {
    this.instrumentTypes = instrumentTypes;
    return this;
  }

  public InstrumentSearchCriteria addInstrumentTypesItem(String instrumentTypesItem) {
    if (this.instrumentTypes == null) {
      this.instrumentTypes = new ArrayList<>();
    }
    this.instrumentTypes.add(instrumentTypesItem);
    return this;
  }

  /**
   * Get instrumentTypes
   * @return instrumentTypes
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INSTRUMENT_TYPES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getInstrumentTypes() {
    return instrumentTypes;
  }


  @JsonProperty(value = JSON_PROPERTY_INSTRUMENT_TYPES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInstrumentTypes(@javax.annotation.Nullable List<String> instrumentTypes) {
    this.instrumentTypes = instrumentTypes;
  }


  public InstrumentSearchCriteria segments(@javax.annotation.Nullable List<String> segments) {
    this.segments = segments;
    return this;
  }

  public InstrumentSearchCriteria addSegmentsItem(String segmentsItem) {
    if (this.segments == null) {
      this.segments = new ArrayList<>();
    }
    this.segments.add(segmentsItem);
    return this;
  }

  /**
   * Get segments
   * @return segments
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SEGMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getSegments() {
    return segments;
  }


  @JsonProperty(value = JSON_PROPERTY_SEGMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSegments(@javax.annotation.Nullable List<String> segments) {
    this.segments = segments;
  }


  public InstrumentSearchCriteria isins(@javax.annotation.Nullable List<String> isins) {
    this.isins = isins;
    return this;
  }

  public InstrumentSearchCriteria addIsinsItem(String isinsItem) {
    if (this.isins == null) {
      this.isins = new ArrayList<>();
    }
    this.isins.add(isinsItem);
    return this;
  }

  /**
   * Get isins
   * @return isins
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ISINS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getIsins() {
    return isins;
  }


  @JsonProperty(value = JSON_PROPERTY_ISINS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsins(@javax.annotation.Nullable List<String> isins) {
    this.isins = isins;
  }


  public InstrumentSearchCriteria tradingSymbols(@javax.annotation.Nullable List<String> tradingSymbols) {
    this.tradingSymbols = tradingSymbols;
    return this;
  }

  public InstrumentSearchCriteria addTradingSymbolsItem(String tradingSymbolsItem) {
    if (this.tradingSymbols == null) {
      this.tradingSymbols = new ArrayList<>();
    }
    this.tradingSymbols.add(tradingSymbolsItem);
    return this;
  }

  /**
   * Get tradingSymbols
   * @return tradingSymbols
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TRADING_SYMBOLS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getTradingSymbols() {
    return tradingSymbols;
  }


  @JsonProperty(value = JSON_PROPERTY_TRADING_SYMBOLS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTradingSymbols(@javax.annotation.Nullable List<String> tradingSymbols) {
    this.tradingSymbols = tradingSymbols;
  }


  public InstrumentSearchCriteria weekly(@javax.annotation.Nullable Boolean weekly) {
    this.weekly = weekly;
    return this;
  }

  /**
   * Get weekly
   * @return weekly
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WEEKLY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getWeekly() {
    return weekly;
  }


  @JsonProperty(value = JSON_PROPERTY_WEEKLY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWeekly(@javax.annotation.Nullable Boolean weekly) {
    this.weekly = weekly;
  }


  public InstrumentSearchCriteria provider(@javax.annotation.Nullable String provider) {
    this.provider = provider;
    return this;
  }

  /**
   * Get provider
   * @return provider
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROVIDER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getProvider() {
    return provider;
  }


  @JsonProperty(value = JSON_PROPERTY_PROVIDER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProvider(@javax.annotation.Nullable String provider) {
    this.provider = provider;
  }


  /**
   * Return true if this InstrumentSearchCriteria object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InstrumentSearchCriteria instrumentSearchCriteria = (InstrumentSearchCriteria) o;
    return Objects.equals(this.queries, instrumentSearchCriteria.queries) &&
        Objects.equals(this.exchanges, instrumentSearchCriteria.exchanges) &&
        Objects.equals(this.instrumentTypes, instrumentSearchCriteria.instrumentTypes) &&
        Objects.equals(this.segments, instrumentSearchCriteria.segments) &&
        Objects.equals(this.isins, instrumentSearchCriteria.isins) &&
        Objects.equals(this.tradingSymbols, instrumentSearchCriteria.tradingSymbols) &&
        Objects.equals(this.weekly, instrumentSearchCriteria.weekly) &&
        Objects.equals(this.provider, instrumentSearchCriteria.provider);
  }

  @Override
  public int hashCode() {
    return Objects.hash(queries, exchanges, instrumentTypes, segments, isins, tradingSymbols, weekly, provider);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InstrumentSearchCriteria {\n");
    sb.append("    queries: ").append(toIndentedString(queries)).append("\n");
    sb.append("    exchanges: ").append(toIndentedString(exchanges)).append("\n");
    sb.append("    instrumentTypes: ").append(toIndentedString(instrumentTypes)).append("\n");
    sb.append("    segments: ").append(toIndentedString(segments)).append("\n");
    sb.append("    isins: ").append(toIndentedString(isins)).append("\n");
    sb.append("    tradingSymbols: ").append(toIndentedString(tradingSymbols)).append("\n");
    sb.append("    weekly: ").append(toIndentedString(weekly)).append("\n");
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `queries` to the URL query string
    if (getQueries() != null) {
      for (int i = 0; i < getQueries().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%squeries%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getQueries().get(i)))));
      }
    }

    // add `exchanges` to the URL query string
    if (getExchanges() != null) {
      for (int i = 0; i < getExchanges().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sexchanges%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getExchanges().get(i)))));
      }
    }

    // add `instrumentTypes` to the URL query string
    if (getInstrumentTypes() != null) {
      for (int i = 0; i < getInstrumentTypes().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sinstrumentTypes%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getInstrumentTypes().get(i)))));
      }
    }

    // add `segments` to the URL query string
    if (getSegments() != null) {
      for (int i = 0; i < getSegments().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%ssegments%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getSegments().get(i)))));
      }
    }

    // add `isins` to the URL query string
    if (getIsins() != null) {
      for (int i = 0; i < getIsins().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sisins%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getIsins().get(i)))));
      }
    }

    // add `tradingSymbols` to the URL query string
    if (getTradingSymbols() != null) {
      for (int i = 0; i < getTradingSymbols().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%stradingSymbols%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getTradingSymbols().get(i)))));
      }
    }

    // add `weekly` to the URL query string
    if (getWeekly() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sweekly%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWeekly()))));
    }

    // add `provider` to the URL query string
    if (getProvider() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sprovider%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProvider()))));
    }

    return joiner.toString();
  }
}

