/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.market.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.am.portfolio.client.market.model.QuoteChange;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.portfolio.client.market.invoker.ApiClient;
/**
 * MarketDataUpdate
 */
@JsonPropertyOrder({
  MarketDataUpdate.JSON_PROPERTY_TIMESTAMP,
  MarketDataUpdate.JSON_PROPERTY_QUOTES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-27T02:29:36.319987700+05:30[Asia/Calcutta]", comments = "Generator version: 7.18.0")
public class MarketDataUpdate {
  public static final String JSON_PROPERTY_TIMESTAMP = "timestamp";
  @javax.annotation.Nullable
  private Long timestamp;

  public static final String JSON_PROPERTY_QUOTES = "quotes";
  @javax.annotation.Nullable
  private Map<String, QuoteChange> quotes = new HashMap<>();

  public MarketDataUpdate() { 
  }

  public MarketDataUpdate timestamp(@javax.annotation.Nullable Long timestamp) {
    this.timestamp = timestamp;
    return this;
  }

  /**
   * Get timestamp
   * @return timestamp
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getTimestamp() {
    return timestamp;
  }


  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimestamp(@javax.annotation.Nullable Long timestamp) {
    this.timestamp = timestamp;
  }


  public MarketDataUpdate quotes(@javax.annotation.Nullable Map<String, QuoteChange> quotes) {
    this.quotes = quotes;
    return this;
  }

  public MarketDataUpdate putQuotesItem(String key, QuoteChange quotesItem) {
    if (this.quotes == null) {
      this.quotes = new HashMap<>();
    }
    this.quotes.put(key, quotesItem);
    return this;
  }

  /**
   * Get quotes
   * @return quotes
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_QUOTES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, QuoteChange> getQuotes() {
    return quotes;
  }


  @JsonProperty(value = JSON_PROPERTY_QUOTES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuotes(@javax.annotation.Nullable Map<String, QuoteChange> quotes) {
    this.quotes = quotes;
  }


  /**
   * Return true if this MarketDataUpdate object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MarketDataUpdate marketDataUpdate = (MarketDataUpdate) o;
    return Objects.equals(this.timestamp, marketDataUpdate.timestamp) &&
        Objects.equals(this.quotes, marketDataUpdate.quotes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timestamp, quotes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MarketDataUpdate {\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    quotes: ").append(toIndentedString(quotes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `timestamp` to the URL query string
    if (getTimestamp() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stimestamp%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTimestamp()))));
    }

    // add `quotes` to the URL query string
    if (getQuotes() != null) {
      for (String _key : getQuotes().keySet()) {
        if (getQuotes().get(_key) != null) {
          joiner.add(getQuotes().get(_key).toUrlQueryString(String.format(java.util.Locale.ROOT, "%squotes%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

