/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.market.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.portfolio.client.market.invoker.ApiClient;
/**
 * SecurityMetadata
 */
@JsonPropertyOrder({
  SecurityMetadata.JSON_PROPERTY_SECTOR,
  SecurityMetadata.JSON_PROPERTY_INDUSTRY,
  SecurityMetadata.JSON_PROPERTY_MARKET_CAP_VALUE,
  SecurityMetadata.JSON_PROPERTY_MARKET_CAP_TYPE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-27T09:34:10.222147200+05:30[Asia/Calcutta]", comments = "Generator version: 7.18.0")
public class SecurityMetadata {
  public static final String JSON_PROPERTY_SECTOR = "sector";
  @javax.annotation.Nullable
  private String sector;

  public static final String JSON_PROPERTY_INDUSTRY = "industry";
  @javax.annotation.Nullable
  private String industry;

  public static final String JSON_PROPERTY_MARKET_CAP_VALUE = "marketCapValue";
  @javax.annotation.Nullable
  private Long marketCapValue;

  public static final String JSON_PROPERTY_MARKET_CAP_TYPE = "marketCapType";
  @javax.annotation.Nullable
  private String marketCapType;

  public SecurityMetadata() { 
  }

  public SecurityMetadata sector(@javax.annotation.Nullable String sector) {
    this.sector = sector;
    return this;
  }

  /**
   * Get sector
   * @return sector
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SECTOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSector() {
    return sector;
  }


  @JsonProperty(value = JSON_PROPERTY_SECTOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSector(@javax.annotation.Nullable String sector) {
    this.sector = sector;
  }


  public SecurityMetadata industry(@javax.annotation.Nullable String industry) {
    this.industry = industry;
    return this;
  }

  /**
   * Get industry
   * @return industry
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INDUSTRY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getIndustry() {
    return industry;
  }


  @JsonProperty(value = JSON_PROPERTY_INDUSTRY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIndustry(@javax.annotation.Nullable String industry) {
    this.industry = industry;
  }


  public SecurityMetadata marketCapValue(@javax.annotation.Nullable Long marketCapValue) {
    this.marketCapValue = marketCapValue;
    return this;
  }

  /**
   * Get marketCapValue
   * @return marketCapValue
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MARKET_CAP_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getMarketCapValue() {
    return marketCapValue;
  }


  @JsonProperty(value = JSON_PROPERTY_MARKET_CAP_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMarketCapValue(@javax.annotation.Nullable Long marketCapValue) {
    this.marketCapValue = marketCapValue;
  }


  public SecurityMetadata marketCapType(@javax.annotation.Nullable String marketCapType) {
    this.marketCapType = marketCapType;
    return this;
  }

  /**
   * Get marketCapType
   * @return marketCapType
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MARKET_CAP_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getMarketCapType() {
    return marketCapType;
  }


  @JsonProperty(value = JSON_PROPERTY_MARKET_CAP_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMarketCapType(@javax.annotation.Nullable String marketCapType) {
    this.marketCapType = marketCapType;
  }


  /**
   * Return true if this SecurityMetadata object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SecurityMetadata securityMetadata = (SecurityMetadata) o;
    return Objects.equals(this.sector, securityMetadata.sector) &&
        Objects.equals(this.industry, securityMetadata.industry) &&
        Objects.equals(this.marketCapValue, securityMetadata.marketCapValue) &&
        Objects.equals(this.marketCapType, securityMetadata.marketCapType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sector, industry, marketCapValue, marketCapType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SecurityMetadata {\n");
    sb.append("    sector: ").append(toIndentedString(sector)).append("\n");
    sb.append("    industry: ").append(toIndentedString(industry)).append("\n");
    sb.append("    marketCapValue: ").append(toIndentedString(marketCapValue)).append("\n");
    sb.append("    marketCapType: ").append(toIndentedString(marketCapType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `sector` to the URL query string
    if (getSector() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssector%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSector()))));
    }

    // add `industry` to the URL query string
    if (getIndustry() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sindustry%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIndustry()))));
    }

    // add `marketCapValue` to the URL query string
    if (getMarketCapValue() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smarketCapValue%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMarketCapValue()))));
    }

    // add `marketCapType` to the URL query string
    if (getMarketCapType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smarketCapType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMarketCapType()))));
    }

    return joiner.toString();
  }
}

