/*
 * Market Data API Documentation
 * API documentation for the Market Data service providing access to stock quotes, historical data, market indices, brokerage calculations, and more.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@amportfolio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.am.portfolio.client.market.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.am.portfolio.client.market.model.AuditData;
import com.am.portfolio.client.market.model.IndexMetadata;
import com.am.portfolio.client.market.model.StockData;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.am.portfolio.client.market.invoker.ApiClient;
/**
 * StockIndicesMarketData
 */
@JsonPropertyOrder({
  StockIndicesMarketData.JSON_PROPERTY_INDEX_SYMBOL,
  StockIndicesMarketData.JSON_PROPERTY_DATA,
  StockIndicesMarketData.JSON_PROPERTY_METADATA,
  StockIndicesMarketData.JSON_PROPERTY_DOC_VERSION,
  StockIndicesMarketData.JSON_PROPERTY_AUDIT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-27T09:34:10.222147200+05:30[Asia/Calcutta]", comments = "Generator version: 7.18.0")
public class StockIndicesMarketData {
  public static final String JSON_PROPERTY_INDEX_SYMBOL = "indexSymbol";
  @javax.annotation.Nullable
  private String indexSymbol;

  public static final String JSON_PROPERTY_DATA = "data";
  @javax.annotation.Nullable
  private List<StockData> data = new ArrayList<>();

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @javax.annotation.Nullable
  private IndexMetadata metadata;

  public static final String JSON_PROPERTY_DOC_VERSION = "docVersion";
  @javax.annotation.Nullable
  private String docVersion;

  public static final String JSON_PROPERTY_AUDIT = "audit";
  @javax.annotation.Nullable
  private AuditData audit;

  public StockIndicesMarketData() { 
  }

  public StockIndicesMarketData indexSymbol(@javax.annotation.Nullable String indexSymbol) {
    this.indexSymbol = indexSymbol;
    return this;
  }

  /**
   * Get indexSymbol
   * @return indexSymbol
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INDEX_SYMBOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getIndexSymbol() {
    return indexSymbol;
  }


  @JsonProperty(value = JSON_PROPERTY_INDEX_SYMBOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIndexSymbol(@javax.annotation.Nullable String indexSymbol) {
    this.indexSymbol = indexSymbol;
  }


  public StockIndicesMarketData data(@javax.annotation.Nullable List<StockData> data) {
    this.data = data;
    return this;
  }

  public StockIndicesMarketData addDataItem(StockData dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<>();
    }
    this.data.add(dataItem);
    return this;
  }

  /**
   * Get data
   * @return data
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<StockData> getData() {
    return data;
  }


  @JsonProperty(value = JSON_PROPERTY_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setData(@javax.annotation.Nullable List<StockData> data) {
    this.data = data;
  }


  public StockIndicesMarketData metadata(@javax.annotation.Nullable IndexMetadata metadata) {
    this.metadata = metadata;
    return this;
  }

  /**
   * Get metadata
   * @return metadata
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public IndexMetadata getMetadata() {
    return metadata;
  }


  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadata(@javax.annotation.Nullable IndexMetadata metadata) {
    this.metadata = metadata;
  }


  public StockIndicesMarketData docVersion(@javax.annotation.Nullable String docVersion) {
    this.docVersion = docVersion;
    return this;
  }

  /**
   * Get docVersion
   * @return docVersion
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DOC_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDocVersion() {
    return docVersion;
  }


  @JsonProperty(value = JSON_PROPERTY_DOC_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDocVersion(@javax.annotation.Nullable String docVersion) {
    this.docVersion = docVersion;
  }


  public StockIndicesMarketData audit(@javax.annotation.Nullable AuditData audit) {
    this.audit = audit;
    return this;
  }

  /**
   * Get audit
   * @return audit
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AUDIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public AuditData getAudit() {
    return audit;
  }


  @JsonProperty(value = JSON_PROPERTY_AUDIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAudit(@javax.annotation.Nullable AuditData audit) {
    this.audit = audit;
  }


  /**
   * Return true if this StockIndicesMarketData object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StockIndicesMarketData stockIndicesMarketData = (StockIndicesMarketData) o;
    return Objects.equals(this.indexSymbol, stockIndicesMarketData.indexSymbol) &&
        Objects.equals(this.data, stockIndicesMarketData.data) &&
        Objects.equals(this.metadata, stockIndicesMarketData.metadata) &&
        Objects.equals(this.docVersion, stockIndicesMarketData.docVersion) &&
        Objects.equals(this.audit, stockIndicesMarketData.audit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(indexSymbol, data, metadata, docVersion, audit);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StockIndicesMarketData {\n");
    sb.append("    indexSymbol: ").append(toIndentedString(indexSymbol)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    docVersion: ").append(toIndentedString(docVersion)).append("\n");
    sb.append("    audit: ").append(toIndentedString(audit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `indexSymbol` to the URL query string
    if (getIndexSymbol() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sindexSymbol%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIndexSymbol()))));
    }

    // add `data` to the URL query string
    if (getData() != null) {
      for (int i = 0; i < getData().size(); i++) {
        if (getData().get(i) != null) {
          joiner.add(getData().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sdata%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `metadata` to the URL query string
    if (getMetadata() != null) {
      joiner.add(getMetadata().toUrlQueryString(prefix + "metadata" + suffix));
    }

    // add `docVersion` to the URL query string
    if (getDocVersion() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdocVersion%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDocVersion()))));
    }

    // add `audit` to the URL query string
    if (getAudit() != null) {
      joiner.add(getAudit().toUrlQueryString(prefix + "audit" + suffix));
    }

    return joiner.toString();
  }
}

