# coding: utf-8

"""
    Mutual Fund Portfolio API

    REST API for managing mutual fund portfolio data

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from am_parser_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_health_check_health_get(self) -> None:
        """Test case for health_check_health_get

        Health Check
        """
        pass

    def test_root_get(self) -> None:
        """Test case for root_get

        Root
        """
        pass


if __name__ == '__main__':
    unittest.main()
