# coding: utf-8

"""
    Mutual Fund Portfolio API

    REST API for managing mutual fund portfolio data

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from am_parser_client.models.file_upload import FileUpload

class TestFileUpload(unittest.TestCase):
    """FileUpload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FileUpload:
        """Test FileUpload
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FileUpload`
        """
        model = FileUpload()
        if include_optional:
            return FileUpload(
                id = '',
                file_id = '',
                original_filename = '',
                stored_filename = '',
                file_type = 'excel',
                file_path = '',
                parent_id = '',
                sheet_name = '',
                status = 'uploaded',
                file_size = 56,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                error_message = '',
                processing_metadata = am_parser_client.models.processing_metadata.processing_metadata()
            )
        else:
            return FileUpload(
                file_id = '',
                original_filename = '',
                stored_filename = '',
                file_type = 'excel',
                file_path = '',
                file_size = 56,
        )
        """

    def testFileUpload(self):
        """Test FileUpload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
