# coding: utf-8

"""
    Mutual Fund Portfolio API

    REST API for managing mutual fund portfolio data

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from am_parser_client.models.processing_status import ProcessingStatus

class TestProcessingStatus(unittest.TestCase):
    """ProcessingStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProcessingStatus(self):
        """Test ProcessingStatus"""
        # inst = ProcessingStatus()

if __name__ == '__main__':
    unittest.main()
