name: am-market-sdk-flutter CI

on:
  push:
    paths:
      - 'am-market-sdk/flutter-sdk/**'
  pull_request:
    paths:
      - 'am-market-sdk/flutter-sdk/**'

jobs:
  build_and_verify_flutter:
    permissions:
      contents: read
      packages: write
    uses: AM-Portfolio/am-pipelines/.github/workflows/central-sdk-publish.yml@main
    with:
      language: 'flutter'
      working_directory: 'am-market-sdk/flutter-sdk'
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
