name: am-market-sdk CI

on:
  push:
    paths:
      - 'am-market-sdk/java-sdk/**'
  pull_request:
    paths:
      - 'am-market-sdk/java-sdk/**'

jobs:
  build_and_publish_java:
    uses: AM-Portfolio/am-pipelines/.github/workflows/central-build-publish.yml@main
    with:
      language: 'java'
      working_directory: 'am-market-sdk/java-sdk'
      image_name: 'am-market-sdk'
      build_context: '../..'
