name: am-market-data CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'am-market-data/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'am-market-data/**'

jobs:
  build_and_publish:
    uses: AM-Portfolio/am-cicd/.github/workflows/central-build-publish.yml@main
    with:
      language: 'java'
      working_directory: 'am-market-data'
      image_name: 'am-market-data'
