name: am-market-sdk CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'am-market-sdk/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'am-market-sdk/**'

jobs:
  build_and_publish:
    uses: ./.github/workflows/central-build-publish.yml
    with:
      language: 'java'
      working_directory: 'am-market-sdk'
      image_name: 'am-market-sdk'
