name: am-parser CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'am-parser/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'am-parser/**'

jobs:
  build_and_publish:
    uses: ./.github/workflows/central-build-publish.yml
    with:
      language: 'python'
      working_directory: 'am-parser'
      image_name: 'am-parser'
