name: am-parser CI

on:
  push:
    paths:
      - 'am-parser/**'
  pull_request:
    paths:
      - 'am-parser/**'

jobs:
  build_and_publish:
    uses: AM-Portfolio/am-pipelines/.github/workflows/test.yml@main
