name: am-java-parser-sdk CI

on:
  push:
    paths:
      - 'am-market-sdk/java-parser-sdk/**'
  pull_request:
    paths:
      - 'am-market-sdk/java-parser-sdk/**'

jobs:
  build_and_publish_java_parser:
    permissions:
      contents: read
      packages: write
    uses: AM-Portfolio/am-pipelines/.github/workflows/central-sdk-publish.yml@main
    with:
      language: 'java'
      working_directory: 'am-market-sdk/java-parser-sdk'
    secrets: inherit
