name: Market UI Publish

on:
  push:
    branches: ["main", "develop", "test/**"]
    paths:
      - "am_market_ui/**"
  pull_request:
    branches: ["main", "develop", "test/**"]
    paths:
      - "am_market_ui/**"
  workflow_dispatch:

jobs:
  publish:
    name: Publish UI
    permissions:
      contents: read
      packages: write
    uses: AM-Portfolio/am-pipelines/.github/workflows/central-build-publish.yml@develop
    with:
      language: "flutter"
      working_directory: "am_market_ui/live"
      image_name: "am-market-ui"
      preprod_namespace: "am-apps-preprod"
      prod_namespace: "am-apps-prod"
      deploy_prod: true
    secrets: inherit
