name: Market Data Publish

on:
  workflow_dispatch:
  push:
    branches: ["main", "develop", "dev", "test/**", "feature/**", "hotfix/**", "fix/**"]
    paths:
      - "am-market-data/**"
      - "am-common-investment-data/**"
      - ".github/workflows/market-data.yml"
  pull_request:
    branches: ["main", "develop", "dev", "test/**", "feature/**", "hotfix/**", "fix/**"]
    paths:
      - "am-market-data/**"
      - "am-common-investment-data/**"

jobs:
  publish:
    name: Build, Publish and Deploy to Dev
    permissions:
      contents: write
      packages: write
      id-token: write
    uses: AM-Portfolio/am-pipelines/.github/workflows/central-build-publish-contabo.yml@main
    with:
      language: "java"
      working_directory: "am-market-data"
      image_name: "am-market-data"
      build_context: ".."
      pipelines_ref: "main"
    secrets: inherit
