name: Market Parser Publish

on:
  push:
    branches: ["main", "develop", "feature/**", "fix/**", "hotfix/**", "test/**"]
    paths:
      - "am-parser/**"
  pull_request:
    branches: ["main", "develop", "test/**"]
    paths:
      - "am-parser/**"
  workflow_dispatch:

jobs:
  publish:
    name: Publish Parser
    permissions:
      contents: read
      packages: write
    uses: AM-Portfolio/am-pipelines/.github/workflows/central-build-publish.yml@develop
    with:
      language: "python"
      working_directory: "am-parser"
      image_name: "am-parser"
      preprod_namespace: "am-apps-preprod"
      prod_namespace: "am-apps-prod"
      deploy_prod: true
    secrets: inherit
