name: Market Parser Publish

on:
  push:
    branches: ["main", "develop", "test/**", "feature/**", "hotfix/**", "fix/**"]
    paths:
      - "am-parser/**"
      - ".github/workflows/market-parser.yml"
  pull_request:
    branches: ["main", "develop", "test/**", "feature/**", "hotfix/**", "fix/**"]
    paths:
      - "am-parser/**"
      - ".github/workflows/market-parser.yml"
  workflow_dispatch:

jobs:
  publish:
    name: Publish Parser
    permissions:
      contents: read
      packages: write
    uses: AM-Portfolio/am-pipelines/.github/workflows/central-build-publish-contabo.yml@main
    with:
      language: "python"
      working_directory: "am-parser"
      image_name: "am-parser"
    secrets: inherit
